# seed.py
# This       is your content — the part you edit. build_db.py turns it into recipes.db.
#
# The field-guide blurbs below are starter text written from general knowledge;
# treat seasons/regions as a first draft to tweak to your taste and region.
#
# Ingredient line shapes (used in each recipe's "ingredients" list):
#   {"heading": "Marinade"}                              -> a sub-heading
#   {"qty": "2 tbsp", "text": "olive oil"}               -> plain, non-clickable
#   {"qty": "4 cloves", "item": "garlic",
#    "label": "garlic", "note": ", crushed"}             -> clickable (item = a key below)
#
#   Units in "qty": write liquids measured in ounces as "fl oz" (e.g. "4 fl oz"), NOT
#   bare "oz". The grams converter treats "fl oz" as volume (-> mL -> grams via density)
#   but bare "oz" as weight (28.35 g/oz), so a bare "oz" on a liquid would convert wrongly.
#
# Step shapes (used in each recipe's "steps" list):
#   "Plain sentence with a [[garlic]] link or [[red_onion|red onions]] link."
#   {"heading": "Grill the chicken"}                     -> a sub-heading

# The people who can keep their own version of a recipe. Each gets a display colour
# (any CSS colour value). The original cookbook recipe always shows in the default
# ink; a person's edits and additions show in their colour. Add or rename people here
# and rerun build_db.py — their saved changes are keyed by id, so keep ids stable.
PEOPLE = [
    {"id": "andy",   "name": "Andy",   "color": "#A32D2D"},   # red
    {"id": "vedant", "name": "Vedant", "color": "#534AB7"},   # purple
]

# month numbers: 1=Jan ... 12=Dec   (empty list = treat as a year-round staple)
INGREDIENTS = {
    # ---- fresh produce & aromatics ----
    "lemon": {
        "name": "Lemon",
        "descr": "A winter citrus at its juiciest in the colder months. Meyer lemons are sweeter and floral; Eureka and Lisbon are the tart workhorses.",
        "season": [12, 1, 2, 3, 4],
        "regions": ["California", "Sicily", "Spain", "Argentina"],
        "pairs": "Garlic, olive oil, herbs, chicken, and almost any vegetable.",
    },
    "lime": {
        "name": "Lime",
        "descr": "A tropical citrus, more aromatic and less sour than lemon. Persian limes are the common seedless kind; small key limes are sharper.",
        "season": [5, 6, 7, 8, 9],
        "regions": ["Mexico", "Brazil", "India", "Florida"],
        "pairs": "Fish sauce, chili, cilantro, coconut, and tamarind.",
    },
    "garlic": {
        "name": "Garlic",
        "descr": "A pungent allium bulb, mellowing and sweetening as it cooks. Hardneck types are more intense; softneck store longer.",
        "season": [7, 8, 9],
        "regions": ["California", "China", "Spain", "Argentina"],
        "pairs": "Almost everything savory — onion, ginger, chili, lemon, and olive oil.",
    },
    "ginger": {
        "name": "Ginger",
        "descr": "A knobbly rhizome with bright heat. Young ginger is mild and thin-skinned; mature ginger is fibrous and sharper.",
        "season": [],
        "regions": ["India", "China", "Nigeria", "Indonesia"],
        "pairs": "Garlic, soy, lime, scallions, and chili.",
    },
    "red_onion": {
        "name": "Red Onion",
        "descr": "A milder, sweeter onion that holds its color. Good raw in sliced half-moons; turns jammy and soft when slow-roasted.",
        "season": [7, 8, 9],
        "regions": ["United States", "India", "Egypt", "Netherlands"],
        "pairs": "Sumac, lemon, parsley, and roast meats.",
    },
    "onion": {
        "name": "Onion",
        "descr": "The yellow workhorse allium — sharp raw, deeply savory and sweet once cooked down. Stores for months.",
        "season": [7, 8, 9],
        "regions": ["United States", "India", "China", "Netherlands"],
        "pairs": "Garlic, ginger, cumin, and just about any braise or sauce.",
    },
    "cauliflower": {
        "name": "Cauliflower",
        "descr": "A cool-season brassica. Best when the florets are tight and creamy white; takes well to high-heat roasting until browned.",
        "season": [9, 10, 11, 12, 1, 2, 3],
        "regions": ["India", "China", "California", "Spain"],
        "pairs": "Cumin, turmeric, potato, lemon, and tahini.",
    },
    "potato": {
        "name": "Potato",
        "descr": "Starchy russets are the roasting and frying choice — fluffy inside, crisp at the edges. Harvested late summer to fall, stored year-round.",
        "season": [8, 9, 10],
        "regions": ["Idaho", "Washington", "Northern Europe", "China"],
        "pairs": "Cauliflower, cumin, cilantro, and plenty of salt.",
    },
    "cilantro": {
        "name": "Cilantro",
        "descr": "The leaf of the coriander plant — citrusy and fresh. The stems carry the most flavor, so chop and use them too.",
        "season": [3, 4, 5, 9, 10],
        "regions": ["Grown worldwide as a cool-season herb"],
        "pairs": "Lime, chili, cumin, and ginger.",
    },
    "parsley": {
        "name": "Parsley",
        "descr": "A hardy herb, fresh and grassy. Flat-leaf (Italian) has more flavor than curly and is easier to chop finely.",
        "season": [4, 5, 6, 7, 8, 9, 10],
        "regions": ["Grown worldwide"],
        "pairs": "Lemon, garlic, sumac, and olive oil.",
    },
    "lemongrass": {
        "name": "Lemongrass",
        "descr": "A fibrous tropical stalk with a clean lemon-floral perfume. Only the tender pale bottom is used; bruise or pound it to release the oils.",
        "season": [],
        "regions": ["Thailand", "Vietnam", "Sri Lanka", "India"],
        "pairs": "Garlic, fish sauce, lime, coconut, and chili.",
    },
    "shallot": {
        "name": "Shallot",
        "descr": "A small, fine-grained allium — gentler and sweeter than onion, with a hint of garlic. Good raw in dressings and dipping sauces.",
        "season": [7, 8, 9],
        "regions": ["France", "Southeast Asia", "United States"],
        "pairs": "Fish sauce, lime, herbs, and vinegar.",
    },
    "green_onion": {
        "name": "Green Onion",
        "descr": "Also called scallions — mild allium with crisp white bottoms and grassy green tops. Often stirred in at the very end for freshness.",
        "season": [],
        "regions": ["Grown worldwide year-round"],
        "pairs": "Soy, sesame, ginger, and chili.",
    },
    "spinach": {
        "name": "Spinach",
        "descr": "A tender cool-season green that wilts to almost nothing in seconds of heat. Baby leaves need no trimming.",
        "season": [3, 4, 5, 9, 10, 11],
        "regions": ["China", "United States", "Europe"],
        "pairs": "Garlic, sesame, soy, and lemon.",
    },
    "carrot": {
        "name": "Carrot",
        "descr": "A sweet root vegetable, crunchy raw and good julienned into bowls. Stores for weeks and is available all year.",
        "season": [6, 7, 8, 9, 10],
        "regions": ["China", "Uzbekistan", "United States", "Europe"],
        "pairs": "Ginger, sesame, lime, and fresh herbs.",
    },
    "avocado": {
        "name": "Avocado",
        "descr": "A buttery, oil-rich fruit eaten as a vegetable. Ripe when it yields to gentle pressure; browns quickly once cut, so dress with citrus.",
        "season": [4, 5, 6, 7, 8, 9],
        "regions": ["Mexico", "California", "Peru"],
        "pairs": "Lime, chili, sesame, and leafy greens.",
    },
    "asian_pear": {
        "name": "Asian Pear",
        "descr": "A crisp, round, apple-textured pear. Grated into marinades it adds sweetness and a natural enzyme that helps tenderize meat.",
        "season": [8, 9, 10, 11],
        "regions": ["China", "Korea", "Japan", "California"],
        "pairs": "Soy, sesame, ginger, and beef.",
    },
    "pine_nut": {
        "name": "Pine Nut",
        "descr": "The soft, resinous seed of certain pine cones — laborious to harvest, which is why they're pricey. Toast briefly; they burn fast.",
        "season": [],
        "regions": ["Mediterranean", "China", "Korea"],
        "pairs": "Sumac, parsley, olive oil, and roast meats.",
    },
    # ---- spices & pantry (year-round; season left empty) ----
    "sumac": {
        "name": "Sumac",
        "descr": "Dried, ground berries of the sumac shrub — tangy and lemony with a deep red color. A finishing spice as much as a cooking one.",
        "season": [],
        "regions": ["Levant", "Turkey", "Iran"],
        "pairs": "Red onion, lemon, parsley, chicken, and flatbread.",
    },
    "cumin": {
        "name": "Cumin",
        "descr": "A warm, earthy seed used whole or ground. Toasting whole seeds before grinding deepens the flavor noticeably.",
        "season": [],
        "regions": ["India", "Iran", "the Mediterranean"],
        "pairs": "Cauliflower, potato, turmeric, and chili.",
    },
    "allspice": {
        "name": "Allspice",
        "descr": "A single dried berry that tastes like a blend of cinnamon, clove, and nutmeg — hence the name.",
        "season": [],
        "regions": ["Jamaica", "Central America"],
        "pairs": "Cinnamon, cumin, and slow-cooked meats.",
    },
    "cinnamon": {
        "name": "Cinnamon",
        "descr": "The dried inner bark of a tropical tree. Delicate Ceylon ('true' cinnamon) is milder; cassia is the bolder, common supermarket type.",
        "season": [],
        "regions": ["Sri Lanka", "Indonesia", "Vietnam"],
        "pairs": "Allspice, cumin, and both sweet and savory dishes.",
    },
    "turmeric": {
        "name": "Turmeric",
        "descr": "A golden rhizome, almost always sold dried and ground. Earthy and slightly bitter; it stains everything, including you.",
        "season": [],
        "regions": ["India"],
        "pairs": "Cumin, ginger, cauliflower, and onion.",
    },
    "asafetida": {
        "name": "Asafetida (Hing)",
        "descr": "A dried plant resin, sharp and pungent raw but mellowing into a savory, onion-garlic note when cooked in hot oil. A little goes a long way.",
        "season": [],
        "regions": ["Iran", "Afghanistan", "India"],
        "pairs": "Cumin, turmeric, lentils, and vegetables.",
    },
    "chile_powder": {
        "name": "Red Chile Powder",
        "descr": "Ground dried red chilies — heat plus color. Strength varies wildly by type, so add to taste.",
        "season": [],
        "regions": ["India", "Mexico"],
        "pairs": "Cumin, turmeric, lime, and garlic.",
    },
    "white_pepper": {
        "name": "White Peppercorns",
        "descr": "The ripe peppercorn with its dark skin removed — earthier and less sharp than black pepper, common in Thai and Chinese cooking.",
        "season": [],
        "regions": ["India", "Indonesia", "Vietnam"],
        "pairs": "Coriander seed, garlic, and white sauces.",
    },
    "coriander_seed": {
        "name": "Coriander Seed",
        "descr": "The dried seed of the cilantro plant, warm and citrusy — quite different from the fresh leaf. Toast before grinding.",
        "season": [],
        "regions": ["India", "Eastern Europe", "Morocco"],
        "pairs": "White pepper, cumin, lemongrass, and garlic.",
    },
    "soy_sauce": {
        "name": "Soy Sauce",
        "descr": "A fermented soybean-and-wheat sauce — salty and savory (umami). Light is saltier and thinner; dark is thicker, sweeter, and more for color.",
        "season": [],
        "regions": ["China", "Japan", "Korea"],
        "pairs": "Sesame, ginger, garlic, and sugar.",
    },
    "fish_sauce": {
        "name": "Fish Sauce",
        "descr": "Salted, fermented fish pressed into a clear, savory liquid — the backbone of Southeast Asian seasoning. Smells strong, tastes deep.",
        "season": [],
        "regions": ["Thailand", "Vietnam"],
        "pairs": "Lime, palm sugar, chili, and garlic.",
    },
    "tamarind": {
        "name": "Tamarind",
        "descr": "The sour pulp of a tropical pod, usually sold as paste or concentrate. Brings a fruity tartness to sauces and braises.",
        "season": [],
        "regions": ["India", "Thailand", "Mexico"],
        "pairs": "Palm sugar, fish sauce, lime, and chili.",
    },
    "palm_sugar": {
        "name": "Palm Sugar",
        "descr": "Sugar from the sap of palm trees — softer and more caramel-like than white sugar. Chop or shave it finely so it dissolves.",
        "season": [],
        "regions": ["Thailand", "Indonesia", "India"],
        "pairs": "Tamarind, fish sauce, lime, and chili.",
    },
    "sesame_oil": {
        "name": "Sesame Oil",
        "descr": "Toasted sesame oil is a finishing oil — nutty and aromatic, added near the end rather than used for frying.",
        "season": [],
        "regions": ["China", "Korea", "Japan"],
        "pairs": "Soy, ginger, scallion, and sesame seeds.",
    },
    "sesame_seed": {
        "name": "Sesame Seeds",
        "descr": "Tiny oil-rich seeds, nutty once toasted. White seeds are the common garnish; black are earthier.",
        "season": [],
        "regions": ["India", "Sudan", "Myanmar"],
        "pairs": "Sesame oil, soy, scallion, and rice.",
    },
    "mirin": {
        "name": "Mirin",
        "descr": "A sweet Japanese rice wine used for cooking — adds gloss and gentle sweetness to glazes and sauces.",
        "season": [],
        "regions": ["Japan"],
        "pairs": "Soy, sesame, and grilled meats.",
    },
    "yeast": {
        "name": "Yeast",
        "descr": "A living single-celled fungus that ferments the sugars in dough, producing the gas that makes bread rise. 'Instant' needs no proofing.",
        "season": [],
        "regions": ["Cultivated, not grown seasonally"],
        "pairs": "Flour, water, salt, and time.",
    },
    "bread_flour": {
        "name": "Bread Flour",
        "descr": "A high-protein wheat flour. The extra protein builds more gluten, giving bread its chew and structure.",
        "season": [],
        "regions": ["Milled from hard wheat (North America, Europe)"],
        "pairs": "Yeast, water, and salt.",
    },
}

RECIPES = [
    {
        "id": "mussakhan",
        "name": "Roast Chicken with Sumac and Red Onions (Mussakhan)",
        "author": "Yasmin Khan · Zaitoun",
        "source_url": None,
        "image": "images/mussakhan.jpg",
        "category": "Chicken · Palestinian · Middle Eastern",
        "servings": "4",
        "prep_time": None,
        "cook_time": "35 min (plus 1–3 hr marinating)",
        "total_time": None,
        "descr": "A classic Palestinian dish: spiced, sumac-rubbed chicken roasted over red onions, piled onto flatbread so the juices soak in. A wonderful sharing meal.",
        "notes": None,
        "ingredients": [
            {"qty": "2 lb / 1 kg", "text": "chicken thighs and drumsticks, skin on"},
            {"qty": "3 tbsp", "text": "extra-virgin olive oil, plus more to serve"},
            {"qty": "½ tsp", "item": "cumin", "label": "ground cumin"},
            {"qty": "½ tsp", "item": "allspice", "label": "ground allspice"},
            {"qty": "¼ tsp", "item": "cinnamon", "label": "ground cinnamon"},
            {"qty": "1½ tbsp", "item": "sumac", "label": "sumac", "note": ", plus more to dust"},
            {"qty": "1", "item": "lemon", "label": "lemon", "note": ", juiced"},
            {"qty": "4 cloves", "item": "garlic", "label": "garlic", "note": ", crushed"},
            {"qty": "", "text": "sea salt and freshly ground black pepper"},
            {"qty": "2 large", "item": "red_onion", "label": "red onions", "note": ", finely sliced into half-moons"},
            {"qty": "2 tbsp", "item": "pine_nut", "label": "pine nuts"},
            {"qty": "1 tbsp", "text": "olive oil or any neutral oil"},
            {"qty": "", "text": "naan or Arabic taboon bread, to serve"},
            {"qty": "", "item": "parsley", "label": "chopped parsley leaves"},
        ],
        "steps": [
            "Slash the flesh of each piece of chicken diagonally a few times, about ¾ inch / 2 cm apart, then place in a large bowl or container.",
            "Pour over the olive oil, spices, [[lemon]] juice, [[garlic]], 1½ tsp salt and ¼ tsp pepper, and rub into the meat. Add the [[red_onion|red onions]] and toss together well. Cover and marinate in the fridge for 1–3 hours.",
            "When ready to cook, preheat the oven to 375°F / 190°C.",
            "Transfer the meat to a baking pan and roast about 35 minutes, until the juices run clear when pierced at the thickest part. Cover with foil and rest while you prepare the toppings.",
            "Fry the [[pine_nut|pine nuts]] in the oil for a minute or so until golden, then drain on paper towel.",
            "Toast the bread and top with the chicken and onion. Finish with the pine nuts, a dusting of [[sumac]] and chopped [[parsley]], then drizzle over the roasting juices and a little more olive oil.",
        ],
    },
    {
        "id": "aloo-gobhi",
        "name": "Roasted Aloo Gobhi",
        "author": "Priya Krishna · Indian-ish",
        "source_url": None,
        "image": "images/aloo-gobhi.jpg",
        "category": "Indian · Vegetarian · Vegetables",
        "servings": "4",
        "prep_time": None,
        "cook_time": "45 min",
        "total_time": None,
        "descr": None,
        "notes": None,
        "ingredients": [
            {"qty": "2 medium", "item": "potato", "label": "russet potatoes", "note": ", cut into 2-inch sticks"},
            {"qty": "1 medium head", "item": "cauliflower", "label": "cauliflower", "note": ", cut into small florets"},
            {"qty": "3 + 2 tbsp", "text": "olive oil, divided"},
            {"qty": "1 tsp", "item": "cumin", "label": "cumin seeds"},
            {"qty": "½ tsp", "item": "turmeric", "label": "ground turmeric"},
            {"qty": "1 small", "item": "onion", "label": "yellow onion", "note": ", finely diced"},
            {"qty": "pinch", "item": "asafetida", "label": "asafetida", "note": " (optional, but really great)"},
            {"qty": "pinch", "item": "chile_powder", "label": "red chile powder"},
            {"qty": "1 tbsp", "item": "ginger", "label": "fresh ginger", "note": ", julienned"},
            {"qty": "1 tbsp", "item": "lime", "label": "lime juice", "note": " (about half a lime), plus more if needed"},
            {"qty": "1 tsp", "text": "kosher salt, plus more if needed"},
            {"qty": "½ cup", "item": "cilantro", "label": "fresh cilantro", "note": ", chopped, for garnish"},
        ],
        "steps": [
            "Preheat the oven to 400°F and line a baking sheet with foil.",
            "Spread the [[potato|potatoes]] and [[cauliflower]] on the sheet and toss with 3 tbsp of the oil. Roast in an even layer for 30 minutes, until browned and slightly crisp, tossing once halfway. Set aside to cool.",
            "Meanwhile, warm the remaining 2 tbsp oil in a large sauté pan over medium-high. When it shimmers, add the [[cumin|cumin seeds]] and cook until medium brown, about a minute. Lower to medium and swirl in the [[turmeric]]. Add the [[onion|onion]] and sauté 4–6 minutes, until translucent.",
            "Add the [[asafetida]] (if using), [[chile_powder|red chile powder]] and [[ginger]], and cook another minute.",
            "Stir in the roasted vegetables and any charred bits. Mix gently (don't overmix or the cauliflower falls apart), add the salt, and cook 5–6 minutes more, until tender but not soggy. Off the heat, add the [[lime]] juice; taste and adjust lime and salt.",
            "Garnish with the [[cilantro]].",
        ],
    },
    {
        "id": "gai-yang",
        "name": "Thai BBQ Chicken (Gai Yang)",
        "author": "Hot Thai Kitchen",
        "source_url": "https://hot-thai-kitchen.com/ultimate-bbq-chicken/",
        "image": "images/gai-yang.jpg",
        "category": "Chicken · Thai",
        "servings": "4",
        "prep_time": "20 min",
        "cook_time": "40 min (plus 2 hr+ marinating)",
        "total_time": None,
        "descr": None,
        "notes": None,
        "ingredients": [
            {"qty": "8", "text": "bone-in, skin-on chicken thighs"},
            {"heading": "Marinade"},
            {"qty": "1½ tsp", "item": "white_pepper", "label": "white peppercorns"},
            {"qty": "2 tsp", "item": "coriander_seed", "label": "toasted coriander seeds"},
            {"qty": "1 stalk", "item": "lemongrass", "label": "lemongrass", "note": ", bottom half only, thinly sliced"},
            {"qty": "5 cloves", "item": "garlic", "label": "garlic"},
            {"qty": "3 tbsp", "item": "soy_sauce", "label": "soy sauce"},
            {"qty": "3 tbsp", "item": "fish_sauce", "label": "fish sauce"},
            {"qty": "1 tbsp", "text": "black (dark) soy sauce"},
            {"qty": "1 tbsp", "text": "sugar"},
            {"qty": "½ cup", "text": "water"},
            {"qty": "2 tbsp", "text": "neutral oil"},
            {"heading": "Dipping sauce — Nam Jim Jeaw"},
            {"qty": "2 tbsp", "item": "tamarind", "label": "tamarind paste", "note": ", store-bought or homemade"},
            {"qty": "1 tbsp", "item": "palm_sugar", "label": "palm sugar", "note": ", finely chopped (or light brown sugar)"},
            {"qty": "1 tbsp", "item": "fish_sauce", "label": "fish sauce"},
            {"qty": "1 tbsp", "item": "lime", "label": "lime juice"},
            {"qty": "to taste", "text": "chili flakes"},
            {"qty": "1 tbsp", "item": "shallot", "label": "shallots", "note": ", finely chopped"},
            {"qty": "1 tbsp", "item": "green_onion", "label": "green onion", "note": ", chopped"},
            {"qty": "3 sprigs", "item": "cilantro", "label": "cilantro", "note": ", chopped"},
            {"qty": "1 tbsp", "text": "toasted rice powder"},
        ],
        "steps": [
            "Grind the [[white_pepper|white peppercorns]] and [[coriander_seed|coriander seeds]] to a powder with a mortar and pestle or spice grinder. Add the [[lemongrass]] and [[garlic]] and pound to a fine paste. Transfer to a bowl and stir in the remaining marinade ingredients until the sugar dissolves.",
            "Add the chicken to a zip-top bag or dish, pour over the marinade, and coat well. Press out the air and marinate at least 2 hours or overnight, turning halfway.",
            {"heading": "Make the nam jim jeaw"},
            "Toast raw jasmine or glutinous rice in a dry skillet over high heat, stirring constantly, until dark brown. Cool, then grind to a powder — that's your toasted rice powder.",
            "Combine the [[tamarind]], [[fish_sauce|fish sauce]], [[lime]] juice and [[palm_sugar]]; stir until the sugar dissolves (finely chopped sugar helps).",
            "Stir in the chili flakes and [[shallot|shallots]]. Close to serving, add the [[green_onion|green onion]], [[cilantro]] and toasted rice powder.",
            {"heading": "Grill the chicken"},
            "Pull the chicken out about 45 minutes ahead so it isn't fridge-cold.",
            "Preheat the grill to medium and lay the chicken skin-side up, over cooler spots if your grill has hot spots. Turn the heat to low / medium-low, close the lid, and cook, flipping every 5 minutes, for 18–30 minutes. For large pieces keep the grill around 275–300°F so the outside doesn't burn.",
            "Cook breast to 160°F / 72°C and thighs and drums to 175°F / 80°C — a thermometer helps.",
        ],
    },
    {
        "id": "no-knead-bread",
        "name": "No-Knead Yeast Bread",
        "author": "RecipeTin Eats",
        "source_url": "https://www.recipetineats.com/easy-yeast-bread-recipe-no-knead/",
        "image": "images/no-knead-bread.jpg",
        "category": "Bread",
        "servings": "10",
        "prep_time": "5 min",
        "cook_time": "40 min",
        "total_time": "2 hr 45 min",
        "descr": None,
        "notes": "Use yeast labelled 'instant' or 'rapid rise'. If you only have active dry yeast, dissolve it in the water first (no need to foam), then add the flour and salt and proceed as written.",
        "ingredients": [
            {"qty": "450 g", "item": "bread_flour", "label": "bread flour"},
            {"qty": "2 tsp", "item": "yeast", "label": "instant or rapid-rise yeast"},
            {"qty": "2 tsp", "text": "kosher salt"},
            {"qty": "375 mL", "text": "very warm tap water (up to 130°F)"},
        ],
        "steps": [
            {"heading": "Mix the dough"},
            "Mix the [[bread_flour|flour]], [[yeast]] and salt in a large bowl. Add the water and stir with the handle of a wooden spoon until the flour is incorporated. The dough will be wet and sloppy — not kneadable, but not runny. Adjust with a little more water or flour if needed.",
            {"heading": "Rise"},
            "Cover with cling wrap or a plate and leave on the counter 2–3 hours, until doubled, wobbly like jelly, and bubbly on top. Optional: refrigerate up to 3 days for more flavour. If chilled, let the bowl sit out 45–60 minutes before shaping.",
            {"heading": "Preheat"},
            "Put a Dutch oven (26 cm / 10\" or larger) with its lid in the oven and preheat to 450°F for 30 minutes before baking.",
            {"heading": "Shape & bake"},
            "Sprinkle the work surface with 1 tbsp flour, scrape the dough out, and dust the top with ½ tbsp flour. With a dough scraper, fold the sides inward about 6 times into a rough round — you're mostly deflating bubbles.",
            "Slide a large piece of parchment beside the dough and flip the dough onto it, smooth side up. Reshape into a rough round. Remove the hot pot, use the paper to lower the dough in, and cover with the lid. Bake 30 minutes covered, then 12 minutes uncovered, until deep golden and crisp. Cool on a rack 10 minutes before slicing.",
        ],
    },
    {
        "id": "bulgogi-bowls",
        "name": "Korean Beef Bulgogi Rice Bowls",
        "author": "RecipeTin Eats",
        "source_url": "https://www.recipetineats.com/korean-beef-bulgogi-rice-bowls-the-easy-way/",
        "image": "images/bulgogi-bowls.jpg",
        "category": "Beef · Korean · Rice",
        "servings": "4",
        "prep_time": "15 min",
        "cook_time": "10 min",
        "total_time": None,
        "descr": None,
        "notes": "Mirin — substitute Chinese cooking wine or cooking sake plus ½ tsp brown sugar, or omit for no alcohol.",
        "ingredients": [
            {"qty": "500 g / 1 lb", "text": "beef mince (ground beef)"},
            {"qty": "1 tbsp", "text": "vegetable oil, + 2 tsp (to wilt the spinach)"},
            {"qty": "1 tbsp", "item": "onion", "label": "onion", "note": ", finely grated (~¼ onion)"},
            {"qty": "3 tbsp", "item": "asian_pear", "label": "Asian pear", "note": ", finely grated"},
            {"qty": "3 cloves", "item": "garlic", "label": "garlic", "note": ", finely grated"},
            {"qty": "1 tsp", "item": "ginger", "label": "ginger", "note": ", finely grated"},
            {"qty": "2½ tbsp", "item": "soy_sauce", "label": "soy sauce", "note": " — all-purpose or light"},
            {"qty": "1 tbsp", "item": "sesame_oil", "label": "sesame oil"},
            {"qty": "1 tbsp", "item": "mirin", "label": "mirin"},
            {"qty": "1 tbsp", "text": "brown sugar"},
            {"qty": "⅛ tsp", "text": "black pepper"},
            {"heading": "Rice bowl drizzle sauce"},
            {"qty": "2 tbsp", "item": "soy_sauce", "label": "soy sauce"},
            {"qty": "1 tbsp", "item": "sesame_oil", "label": "sesame oil"},
            {"qty": "2 tsp", "text": "brown sugar"},
            {"qty": "2 tsp", "item": "lime", "label": "lime (or lemon) juice"},
            {"heading": "For the bowls"},
            {"qty": "", "text": "white rice (medium or short grain if you can)"},
            {"qty": "4 large handfuls", "item": "spinach", "label": "baby spinach", "note": " (or chopped greens — cabbage, kale)"},
            {"qty": "1 large", "item": "carrot", "label": "carrot", "note": ", peeled and julienned"},
            {"qty": "1", "item": "avocado", "label": "avocado", "note": ", mashed"},
            {"qty": "1½ cups", "text": "lettuce, torn into bite-size pieces"},
            {"qty": "1 tsp", "item": "sesame_seed", "label": "white sesame seeds"},
            {"qty": "1", "item": "green_onion", "label": "green onion", "note": ", finely sliced"},
        ],
        "steps": [
            "Mix the bulgogi sauce ingredients in one bowl and the rice-bowl drizzle sauce in a separate bowl.",
            "Wilt the [[spinach]]: heat 2 tsp oil in a large non-stick pan over high heat. Add half the spinach, toss with tongs until semi-wilted (~30 sec), then add the rest and toss until wilted (~1 min). Remove to a bowl.",
            "Cook the beef: add 1 tbsp oil to the pan. Still on high heat, add the beef and break it up until no longer raw. Add the bulgogi sauce and simmer rapidly, stirring now and then, until mostly evaporated, then stir until the beef caramelises a little but stays moist.",
            "Build the bowls: rice topped with the beef, spinach, [[carrot]], [[avocado]], lettuce, the drizzle sauce, [[sesame_seed|sesame seeds]] and [[green_onion|green onion]].",
        ],
    },
]
