sonar.organization=abh5227     
sonar.projectKey=abh5227_recipe-app    

sonar.sources=app.py,build_db.py,migrate.py,seed.py,backup.py,static
sonar.tests=tests
sonar.python.version=3.12            
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/recipes.db,**/__pycache__/**