# -*- coding: utf-8 -*-
"""The 60 AGREE-block verdicts, one line at a time. Keyed by sample index."""
R="RIGHT"; W="WRONG"; B="BOTH-OK-AMBIGUOUS"
J = {
 1:(R,"the override row IS Shaoxing wine",""),
 2:(R,"authored 'water' row, exact",""),
 3:(R,"unsalted butter, exact; the parenthetical is a prep note",""),
 4:(R,"Parmesan, exact","⚠ the ROW also claims 'Grana Padano', a different cheese. Row hygiene, not a wrong link here."),
 5:(R,"white wine, exact","⚠ rule-2 row, kinds EMPTY, 120 subclasses, flagged CATEGORY-shaped. Right for a line that names the category."),
 6:(R,"soy sauce, exact",""),
 7:(R,"dark soy sauce, exact and specific",""),
 8:(R,"authored 'sugar' row, exact",""),
 9:(R,"vanilla extract, exact",""),
 10:(R,"dried basil, exact and specific",""),
 11:(R,"dried chickpea, exact; the can alternative is a second option on the line",""),
 12:(R,"egg, exact",""),
 13:(R,"baking powder, exact",""),
 14:(R,"beef broth, exact",""),
 15:(R,"sugar, exact",""),
 16:(R,"cucumber, exact","⚠ the ROW carries article-title junk ('Cucumber plant defense', 'Green cum'). Hygiene, not a wrong link."),
 17:(R,"egg, exact",""),
 18:(R,"all-purpose flour, exact",""),
 19:(R,"heavy cream, exact",""),
 20:(R,"coriander SEED, and the line says seeds. The cilantro leaf row correctly stayed out.",""),
 21:(R,"sea salt, exact",""),
 22:(R,"cinnamon, exact",""),
 23:(B,"both rows are pepper: white pepper exact, peppercorn its parent","⚠ the peppercorn row also answers for 'black pepper', so the parent is over-broad."),
 24:(R,"chickpea, exact","the line is canned and the row is generic. Granularity, not an error."),
 25:(R,"lemon juice, exact",""),
 26:(R,"egg, exact",""),
 27:(B,"cream cheese exact, fresh cheese its parent","⚠ 'fresh cheese' has 58 subclasses and is flagged as answering for 3 things en.wikipedia keeps apart."),
 28:(R,"heavy cream, exact",""),
 29:(R,"vegetable oil, exact","⚠ the ROW claims 'Brunsli', a Swiss cookie. Hygiene."),
 30:(R,"turmeric, and the row's own names include 'ground turmeric'",""),
 31:(R,"ground cinnamon, exact and specific",""),
 32:(R,"unsalted butter, exact",""),
 33:(R,"egg, exact",""),
 34:(R,"egg yolk, exact","⚠ the ROW claims 'Amanita caesarea', a mushroom. Hygiene."),
 35:(B,"garlic and Allium sativum are the same plant","⚠ the garlic row claims 'artificial intelligence' and 'AI'. Hygiene, badly."),
 36:(R,"kosher salt, exact",""),
 37:(R,"vegetable oil, exact",""),
 38:(W,"⚠ THE ROW IS THE CHILI PEPPER, THE LINE IS A CUP OF SAUCE",
     "Q512580 'piri piri' is P279 chili pepper / cultivar. It claims 'Piri-piri sauce' and "
     "'Peri-peri (Portuguese sauce)' through a WIKIPEDIA REDIRECT, and no separate sauce row "
     "exists. Both matchers land here confidently because the whole phrase 'piri piri sauce' "
     "IS an index key on the pepper row. This is the shared-index failure."),
 39:(R,"pumpkin pie spice, exact",""),
 40:(R,"baking soda, exact",""),
 41:(R,"chicken bone, exact",""),
 42:(R,"granulated sugar, exact","⚠ the ROW claims 'sand'. Hygiene."),
 43:(R,"carrot, exact",""),
 44:(R,"baking powder, exact",""),
 45:(B,"Allium sativum and garlic clove are both garlic",""),
 46:(R,"all-purpose flour, exact",""),
 47:(R,"glutinous rice flour, exact and specific",""),
 48:(R,"baking powder, exact",""),
 49:(B,"Welsh onion and scallion are the same plant under two naming traditions",
     "LOW. Allium fistulosum is what US scallions usually are, but the two rows are kept "
     "apart by Wikidata and I am judging them equivalent for cooking, not for botany."),
 50:(R,"cumin, and 'ground' is a form word",""),
 51:(R,"Shaoxing wine, exact",""),
 52:(R,"light soy sauce, exact and specific",""),
 53:(R,"sugar, exact",""),
 54:(B,"Coriandrum sativum and cilantro are the same herb","the coriander SEED row correctly stayed out."),
 55:(R,"honey, the first of three alternatives the line offers",
     "LOW. molasses and barley malt syrup are equally named and get no row. Defensible, not certain."),
 56:(R,"kosher salt, exact",""),
 57:(R,"extra virgin olive oil, exact and specific",""),
 58:(R,"olive oil, exact","⚠ the ROW claims 'extra virgin', which collides with the EVOO row."),
 59:(R,"authored 'pasta' row, exact",""),
 60:(B,"Allium sativum and garlic clove are both garlic",""),
}
