# -*- coding: utf-8 -*-
"""SCRATCH. Hand verdicts on every row the P279 rule would newly admit.

METHOD, stated so the reader can discount it: every canonical name was read. The verdict
comes from the NAME, not from opening the Wikidata item, so a name that reads as a bread
is called a bread. Where the name alone does not settle it the verdict is BORDERLINE and
that is not a hedge, it is the honest answer for a thing sold dry and also served plated.

FOUR verdicts, not the three asked for. 'Category article' and 'product-code string' are
neither a dry good nor a dish and calling them DISH would misreport what they are.
"""
# ── ⚠️ NOT-AN-ITEM: nothing a recipe line can name ───────────────────────────
NOT_ITEM = {
 # product-classification strings, Russian OKPD, lifted whole
 "Изделия макаронные короткие из пшеничной муки прочие":"Russian OKPD product-code string",
 "вермишель длинная":"Russian OKPD product-code string",
 "вермишель короткая":"Russian OKPD product-code string",
 "вермишель короткая, изготовленная из муки твердой пшеницы высшего сорта":"Russian OKPD product-code string",
 "вермишель короткая, изготовленная из муки твердой пшеницы высшего сорта с добавками":"Russian OKPD product-code string",
 "вермишель короткая, изготовленная из пшеничной хлебопекарной муки высшего сорта":"Russian OKPD product-code string",
 "вермишель короткая, изготовленная из пшеничной хлебопекарной муки высшего сорта с добавками":"Russian OKPD product-code string",
 "изделия макаронные фигурные":"Russian OKPD product-code string",
 "макароны, изготовленные из муки твердой пшеницы высшего сорта":"Russian OKPD product-code string",
 "макароны, изготовленные из муки твердой пшеницы высшего сорта с добавками":"Russian OKPD product-code string",
 "аришта":"Russian OKPD product-code string","лапша короткая":"Russian OKPD product-code string",
 "narrow lapsha":"Russian OKPD product-code string","wide lapsha":"Russian OKPD product-code string",
 # metaclasses: a class of shapes, not a shape
 "long macaroni products":"metaclass, a class of shapes not a shape",
 "short macaroni products":"metaclass, a class of shapes not a shape",
 "tube-shaped macaroni products":"metaclass, a class of shapes not a shape",
 "string-like macaroni products":"metaclass, a class of shapes not a shape",
 "extruded noodle":"metaclass, a manufacturing class not a product",
 "hand noodle":"metaclass, a manufacturing class not a product",
 "knife-cut noodle":"metaclass, a manufacturing class not a product",
 "ribbon noodle":"metaclass, a shape class not a product",
 "stuffed pasta":"metaclass, a class of shapes not a shape",
 "Italian stuffed pasta":"metaclass, a class of shapes not a shape",
 "durum wheat pasta":"metaclass, a class of shapes not a shape",
 "wholemeal pasta":"metaclass, a class of shapes not a shape",
 "egg pasta":"metaclass, a class of shapes not a shape",
 "black noodles":"metaclass, a colour class not a product",
 "cold noodle":"metaclass, a serving-temperature class",
 "type of pasta":"metaclass, Wikidata's own class node",
 "leavened bread":"metaclass, a leavening class not a bread",
 "unleavened bread":"metaclass, a leavening class not a bread",
 "ungesäuertes Brot":"metaclass, German for unleavened bread",
 "yeast bread":"metaclass, a leavening class not a bread",
 "quick bread":"metaclass, a leavening class not a bread",
 "hearth bread":"metaclass, a baking-method class",
 "floor-baked bread":"metaclass, a baking-method class",
 "steamed bread":"metaclass, a cooking-method class",
 "batter bread":"metaclass, a dough-type class",
 "sweet bread":"metaclass, a taste class not a bread",
 "fruit bread":"metaclass, an inclusion class not a bread",
 "multigrain bread":"metaclass, a grain class not a bread",
 "sprouted bread":"metaclass, a grain-treatment class",
 "shelf-stable bread":"metaclass, a storage class",
 "pre-baked bread":"metaclass, a supply-chain class",
 "crustless bread":"metaclass, a trimming class",
 "sliced bread":"metaclass, a format class",
 "homemade bread":"metaclass, a provenance class",
 "electric bread":"metaclass, an appliance class",
 "twist bread":"metaclass, a shaping class",
 "Slow Bread":"metaclass, a method class",
 "parbaking":"a PROCESS, not a thing",
 "bread crumbs":"duplicate of the existing 'breadcrumbs' row",
 # country and period articles: en.wikipedia list pages, not foods
 "Bröd i Finland":"category article, Swedish for 'bread in Finland'",
 "Chléb ve starověkém Egyptě":"category article, Czech for 'bread in ancient Egypt'",
 "Turkish breads":"category article","South Asian bread":"category article",
 "Indian bread":"category article","German bread":"category article",
 "Georgian bread":"category article","Finnish bread":"category article",
 "Mexican bread":"category article","Pakistani bread":"category article",
 "Maltese bread":"category article","Spanish bread":"category article",
 "Afghan bread":"category article","Canadian white bread":"category article",
 "Swedish white bread":"category article","Valladolid bread":"category article",
 "Japanese noodles":"category article","Korean noodles":"category article",
 "Chinese noodles":"category article","Vietnamese noodles":"category article",
 "Three Great Noodles of Morioka":"category article, a tourism list",
 "Campanian pasta":"category article","Pastas de pescado":"category article",
 "Pasta seca":"category article, Spanish for 'dry pasta'",
 "Turkish mantı":"category article, a national variant page",
 "Sorrentinos argentinos":"category article, a national variant page",
 "Bush bread":"category article, an anthropology page",
 "Altbrot":"a bakery WASTE stream, stale bread returned into new dough",
 # ritual and heritage entries
 "ritual bread baking on St. George’s day in the village of Krynychne":
     "an intangible-cultural-heritage listing, not a food",
 "Christmas wafer":"a religious object","prosphora":"a religious object",
 "sacramental bread":"a religious object","blessed bread":"a religious object",
 "artos":"a religious object","fermentum":"a religious object",
 "Viaticum":"a religious rite","mola salsa":"a Roman ritual meal offering",
 "koliva":"a funeral rite dish, not an ingredient",
 "Gebildbrot":"a folklore CATEGORY of figural breads",
 "Pope Ladies":"a folklore figural bread, a custom not a staple",
 "Bappir":"ancient Sumerian beer bread, known only from tablets",
 "Firecake":"a Revolutionary-War ration, historical",
 "Kanpan":"a Japanese emergency ration, not a cooking ingredient",
 "Chléb":"category article","Viaticum ":"a religious rite",
 # brands
 "Wonder Bread":"a BRAND","Holsum Bread":"a BRAND","A1 Bread":"a BRAND",
 "Ghandi Bread":"a BRAND","Dosirac":"a BRAND of instant noodle",
 "Casinobread":"a BRAND","Holsum":"a BRAND","National loaf":"a WWII ration spec",
 "Grant loaf":"a named 1940s recipe, not a product",
 "Cornell bread":"a named institutional formula, not a product",
 "Vantage loaf":"a named formula, not a product",
 "Weltmeisterbrot":"a competition title, not a product",
 "Weltmeisterbrötchen":"a competition title, not a product",
 "Purple Bread":"a 2016 research prototype, never a product",
 # not food at all
 "bread dildo":"not a food","spread":"the wrong sense entirely, a condiment class",
 "sandwich topping":"a Dutch category for what goes ON bread",
 "soldiers":"toast cut into strips, a serving format",
 "Toast point":"a serving format","dim sum":"a MEAL CATEGORY, dozens of dishes",
 "burger":"a sandwich, and the row is the whole burger",
 "sandwich":"a finished sandwich","sealed crustless sandwich":"a finished sandwich",
 "Archipelago bread":"a category article","Kolot":"a category article",
}
# ── ⚠️ DISH: cooked and plated ───────────────────────────────────────────────
DISH = {
 # pasta and dumpling dishes
 "Gnocchi alla sorrentina":"a baked gnocchi dish","gnocchi alla romana":"a baked semolina dish",
 "Pasta all'Ortolana":"a sauced pasta dish","Pasta mollicata":"a sauced pasta dish",
 "chicken riggies":"a sauced pasta dish","toasted ravioli":"a fried appetizer",
 "crab rangoon":"a fried appetizer","matriciani":"a sauced pasta dish",
 "maccheroni alla molinara":"a sauced pasta dish","spaghetti alla chitarra":"a regional dish page",
 "Ba-wan":"a steamed Taiwanese dumpling dish","Chiburekki":"a fried turnover dish",
 "Khuushuur":"a fried Mongolian turnover","Boraki":"a fried Armenian dumpling dish",
 "Corunda":"a steamed tamale dish","Pamonha":"a steamed corn dish",
 "Songpyeon":"a steamed rice cake dish","Sebada":"a fried stuffed pastry dish",
 "Kenkey":"a fermented maize dumpling dish","dango":"a skewered sweet dish",
 "gujia":"a fried sweet turnover","empanada":"a filled baked turnover",
 "Niflettes":"a French pastry","Pizzarelle":"a fried sweet",
 "garlic chives pocket":"a filled griddle cake dish","banana pasta":"a novelty dish",
 "zoodle":"spiralized courgette, a preparation not a product",
 "spinach noodles":"a coloured fresh pasta dish page","kale noodles":"a novelty dish",
 "Kalsonnes b'rishta":"a composed dish","Farfel":"a soup garnish preparation",
 "Fidés de Saboya":"a regional dish page","Gilun":"a regional dish page",
 "Filindeu":"a ritual soup dish","Crouzets":"a regional dish page",
 "Kalduny":"a filled dumpling dish","Kasnudeln":"a filled dumpling dish",
 "Schlutzkrapfen":"a filled dumpling dish","Maultasche":"a filled dumpling dish",
 "Šúľance":"a sweet potato-dough dish","lebbencs":"a soup dish",
 "stroncatura":"a regional dish page","potato gnocchi":"a fresh dish",
 "Fiorentine":"a regional dish page","Scifuloti":"a regional dish page",
 "tumbarella":"a regional dish page","parmatieddi":"a regional dish page",
 "ingannapreti":"a regional dish page","testaroli":"a griddle-cooked dish",
 "gogges":"a regional dish page","cavata":"a regional dish page",
 "Curzoli":"a regional dish page","Fusi":"a regional dish page",
 "chaoshou":"a wonton soup dish","luosifen":"a noodle soup dish",
 "toast":"toasted bread, a preparation","French toast":"a cooked dish",
 "Cinnamon Toast":"a cooked dish","honey toast":"a cooked dish",
 "pizza toast":"a cooked dish","Ogura toast":"a cooked dish",
 "picatostes":"fried bread, a dish","švejkovská topinka":"a fried-bread dish",
 "fried bread":"a cooked dish","garlic bread":"a cooked dish",
 "Korean cream cheese garlic bread":"a cooked dish",
 "hot and spicy cheese bread":"a cooked dish","cheesymite scroll":"a filled bakery item",
 "medianoche":"a pressed sandwich","chōripan":"a sausage sandwich",
 "Kitakata Ramen Burger":"a novelty sandwich","hoagie roll":"named for the sandwich",
 "hot dog bun":"a roll, but the row is the assembled item",
 "Chakhchoukha":"a torn-bread stew","fit-fit":"a torn-bread dish",
 "sopa paraguaya":"a baked cornbread dish","lángos":"a fried dough dish",
 "Kutia":"a ritual grain dish","Puran Poli":"a stuffed griddle dish",
 "Cochinito de Piloncillo":"a shaped sweet bread, a bakery item",
 "gnocco fritto":"a fried dough dish","Alur papad":"a fried snack",
 "Chaler papad":"a fried snack","Mug daler papad":"a fried snack",
 "Saboor papad":"a fried snack","frybread":"a fried dough dish",
 "damper":"a campfire dish","Adobe bread":"an oven-method page",
 "Kepta duona":"fried bread sticks, a bar snack","Stomp":"a mashed dish",
 "Dumb bread":"a divination custom","tortilla de rescoldo":"an ember-baked dish",
 "khanom bueang":"a filled crisp pancake dish","Chinese pancake":"a cooked dish",
 "hornazo":"a filled meat pie","Sylheti Handesh":"a fried sweet",
 "Trivandrum Boli":"a filled sweet flatbread dish","Ottupathal":"a steamed dish",
 "Sanna":"a steamed rice cake dish","Siddu":"a steamed stuffed bread dish",
 "Guagua de pan":"a figural festival bread","fukuregashi":"a steamed sweet",
 "bungeoppang":"a filled griddle sweet","gukhwa-ppang":"a filled griddle sweet",
 "kkulppang":"a fried filled sweet","soboro-ppang":"a topped sweet bun",
 "Ttongppang":"a novelty filled bun","yakisobapan":"a filled roll, a dish",
 "korokkepan":"a filled roll, a dish","curry bread":"a filled fried roll, a dish",
 "koppe pan":"a split roll for filling, sold as a dish",
 "peanut butter bun":"a filled sweet bun","coconut bun":"a filled sweet bun",
 "pineapple bun":"a topped sweet bun","anpan":"a filled sweet bun",
 "melonpan":"a topped sweet bun","cream roll":"a filled pastry",
 "Blaukrautschnecke":"a filled savoury pastry","Kruidbroodje":"a filled savoury pastry",
 "Tiroler Schinkenkruste":"a ham-filled loaf, a dish",
 "sausage bread":"a filled loaf, a dish","onion bread":"a topped loaf",
 "Cheesymite":"a filled bakery item","garlic knot":"a cooked dish",
 "monkey bread":"a pull-apart sweet dish","king cake":"a festival cake",
 "Vasilopita":"a festival cake with a coin in it","Mona de Pascua":"a festival cake",
 "Colomba di Pasqua":"a festival cake","pizza di Pasqua":"a festival cake",
 "Pizza dolce di Beridde":"a festival cake","Amish Friendship Bread":"a named recipe",
 "Apple Bread":"a named recipe","banana bread":"a home-baked cake",
 "zucchini bread":"a home-baked cake","pumpkin bread":"a home-baked cake",
 "carrot bread":"a home-baked cake","beer bread":"a home-baked loaf",
 "Rotweinbrot":"a home-baked cake","olive bread":"a home-baked loaf",
 "Red bread":"a novelty loaf","Cocol":"a festival bread",
 "pan de muerto":"a festival bread","pan di ramerino":"a festival bread",
 "roscón de reyes":"a festival cake","rosca chonchina":"a festival bread",
 "Roscos de Semana Santa":"a festival sweet","koulouria":"a festival ring bread",
 "Kandil simidi":"a festival ring bread","Colaci":"a festival bread",
 "Sakhnovshchyna korovai":"a wedding bread","korovai":"a wedding bread",
 "kalach":"a festival bread","paska":"an Easter bread",
 "Easter bread":"a festival category","Cougnou":"a festival figural bread",
 "Duivekater":"a festival figural bread","Mutschel":"a festival figural bread",
 "kerststol":"a festival loaf","kersttimp":"a festival loaf",
 "ljochtmisbrea":"a festival loaf","Pinca":"a festival loaf",
 "Colston bun":"a festival bun","hot cross bun":"a festival bun",
 "Iced bun":"a finished bakery item","currant bun":"a finished bakery item",
 "Sally Lunn bun":"a finished bakery item","cinnamon roll":"a finished bakery item",
 "sweet roll":"a finished bakery item","maritozzo":"a filled sweet bun",
 "sufganiyah":"a filled fried doughnut","Krachel":"a sweet bun",
 "Cachitos":"a filled sweet roll","Tequeño":"a fried cheese stick",
 "pão de queijo":"a cheese-dough roll, baked to order","almojábana":"a cheese roll",
 "Pandebono":"a cheese roll","chipa":"a cheese roll","Chipa cuiabana":"a cheese roll",
 "pan de yuca":"a cheese roll","Mandoca":"a fried ring",
 "rosquilla":"a fried ring sweet","rosquillas de Ledesma":"a fried ring sweet",
 "rosquillas de San Froilán":"a fried ring sweet","rosquillas de Santa Clara":"a fried ring sweet",
 "rosquillas tontas y listas":"a fried ring sweet","Rosquillas de Alhama":"a fried ring sweet",
 "roscos del Santo":"a fried ring sweet","rosca madrileña":"a fried ring sweet",
 "Rosca":"a fried ring sweet","roscón":"a festival cake",
 "rosquilla ":"a fried ring sweet","Cuccalar":"a regional sweet",
 "Sorullos":"a fried corn stick","Güirila":"a fresh-corn griddle cake",
 "totoposte":"a toasted snack","Papad":"a fried snack","papad":"a fried snack",
 "biscoito":"a baked snack","biskotso":"a twice-baked snack",
 "Galleta forta":"a hard biscuit","Cocchia":"a regional bread dish",
 "Casatiello":"a filled festival loaf","Panbrioche":"a bakery item",
 "veneziana":"a topped sweet bun","panettone":"a festival cake",
 "Pandoro":"a festival cake","stollen":"a festival loaf","babka":"a filled sweet loaf",
 "Cozonac":"a filled sweet loaf","Bisciola PAT":"a fruit loaf",
 "malt loaf":"a finished bakery loaf","barmbrack":"a fruit loaf",
 "bara brith":"a fruit loaf","raisin bread":"a finished bakery loaf",
 "rozijnenbrood":"a finished bakery loaf","vruchtenbrood":"a finished bakery loaf",
 "Suikerbrood":"a finished bakery loaf","kulich":"an Easter cake",
 "Anello di Monaco":"a filled ring cake","Trenza":"a filled sweet plait",
 "Trenza de Almudévar":"a filled sweet plait","brioche tressée de Metz":"a bakery item",
 "Zopf":"a finished bakery plait","barkis":"a finished bakery plait",
 "choereg":"a festival sweet bread","Saint George bread":"a festival bread",
 "Ungarisches Teebrot":"a tea loaf","Karlsbaderbröd":"a sweet bakery item",
 "Nobisbröd":"a meringue confection","Krotekake":"a festival cake",
 "Kavelgris":"a festival bread","Perlenka":"a sweet plait",
 "Senfzwirbel":"a filled savoury pastry","Blaa":"a finished bakery roll",
 "Buttery":"a finished bakery roll","Scuffler":"a finished bakery item",
 "stottie cake":"a finished bakery item","barm cake":"a finished bakery roll",
 "Hoggan":"a filled pasty","Ganzuki":"a steamed sweet",
 "Balep korkun":"a griddle bread dish","Katlam":"a layered fried bread dish",
 "Kattama":"a layered fried bread dish","Msemmen":"a layered fried bread dish",
 "mahjouba":"a stuffed griddle bread dish","Bolani":"a stuffed griddle bread dish",
 "qistibi":"a stuffed griddle bread dish","Gobhi paratha":"a stuffed griddle bread dish",
 "aloo paratha":"a stuffed griddle bread dish","dholl puri":"a stuffed griddle bread dish",
 "Dalpuri":"a stuffed griddle bread dish","puri":"a fried bread dish",
 "Sel roti":"a fried ring bread dish","Poee":"a regional bread dish",
 "Pathiri":"a griddle bread dish","Akki rotti":"a griddle bread dish",
 "Jolada Rotti":"a griddle bread dish","Chhilka Roti":"a griddle bread dish",
 "Rumali Roti":"a griddle bread dish","Laobing":"a griddle bread dish",
 "Guokui":"a griddle bread dish","Youbing":"a fried bread dish",
 "shaobing":"a baked layered bread dish","Kaomianjin":"a grilled gluten dish",
 "Erzurum kadaifi dolması":"a stuffed dessert dish","Kadayif":"a syrup dessert",
 "Khanom":"a sweet dish","fios de ovos":"a sweet egg-thread confection",
 "Cuban bread":"a regional loaf, sold baked","pancha":"a regional bread dish",
 "musafan":"a regional bread dish","Heftbirrî":"a regional bread dish",
 "Fatoot":"a torn-bread dish","Chapla bread":"a griddle bread dish",
 "Al-Maltout":"a regional bread dish","fatira":"a layered pastry dish",
 "Kubaneh":"an overnight baked dish","Malooga":"a griddle bread dish",
 "Bolo do caco":"a griddle bread dish","Bolo de Milho de Paraduça, Vale de Cambra":"a regional cake",
 "Caramanduca":"a regional sweet bread","Fogaça da Feira":"a festival sweet bread",
 "Folar":"a festival bread","Arrufadas de Coimbra":"a sweet bread",
 "Broa de Avintes":"a regional loaf","pão brote":"a regional loaf",
 "Pada de Vale de Ílhavo":"a regional loaf","Pa del Pamano":"a regional loaf",
 "Pa de Tramuntana":"a regional loaf","Penia":"a festival bread",
 "Mafalda (cucina)":"a regional loaf","Rundìtt":"a regional bread dish",
 "Montasù PAT":"a regional loaf","Spuccadella":"a regional roll",
 "Fugassa veneta PAT":"a festival cake","Buccellato di Lucca":"a festival ring cake",
 "pane parruozzo":"a regional cake","Vastedda":"a regional bread dish",
 "Vasteḍḍa":"a regional bread dish","schiacciata":"a topped flatbread dish",
 "panigaccio":"a griddle bread dish","piadina":"a griddle flatbread dish",
 "Piadina":"a griddle flatbread dish","Sanchuisanda":"a regional dish page",
 "Kaak":"a ring bread","ka'ak al-Quds":"a street-food ring bread",
 "simit":"a street-food ring bread","obwarzanek":"a street-food ring bread",
 "Obwarzanek krakowski":"a street-food ring bread","bublik":"a ring bread",
 "Covrigi":"a street-food ring bread","Simid":"a ring bread",
 "kifli":"a finished bakery roll","Geflochtener Gipfel":"a bakery plait",
 "Weggli":"a bakery roll","Bürli":"a bakery roll","Langsemmel":"a bakery roll",
 "michetta":"a bakery roll","ciriola":"a bakery roll","pistolet":"a bakery roll",
 "bolillo":"a bakery roll","birote":"a bakery roll","telera":"a bakery roll",
 "Marraqueta":"a bakery roll","Hallulla":"a bakery roll","Pandesal":"a bakery roll",
 "Pinagong":"a bakery roll","Mandarin roll":"a bakery roll",
 "Parker House roll":"a bakery roll","dinner roll":"a bakery roll",
 "Onion roll":"a bakery roll","Bulkie roll":"a bakery roll",
 "sesame roll":"a bakery roll","muesli roll":"a bakery roll",
 "mueslibol":"a bakery roll","quark roll":"a bakery roll",
 "Scottish Morning Roll":"a bakery roll","rundstykke":"a bakery roll",
 "Vollkornbrötchen":"a bakery roll","Schusterjunge":"a bakery roll",
 "Italiaanse bol":"a bakery roll","Zuidlaarderbol":"a bakery roll",
 "beschuitbol":"a bakery roll","krokantbrood":"a bakery loaf",
 "Rotterdams waterbroodje":"a bakery roll","puntbrood":"a bakery loaf",
 "knipbrood":"a bakery loaf","builbrood":"a bakery loaf","gistbrood":"a bakery loaf",
 "hardbrood":"a bakery loaf","moutbrood":"a bakery loaf","tarwebrood":"a bakery loaf",
 "maanzaadbrood":"a bakery loaf","zonnebloempittenbrood":"a bakery loaf",
 "Sonnenblumenkernbrot":"a bakery loaf","Honig-Salz-Brot":"a bakery loaf",
 "Ölbrot":"a bakery loaf","Dinkelbread":"a bakery loaf","Burebrot":"a bakery loaf",
 "St. Galler brot":"a bakery loaf","Basler Brot":"a bakery loaf",
 "Schweizer Zeilenbrot":"a bakery loaf","cuchaule":"a festival loaf",
 "Kasseler Brot":"a bakery loaf","Paderborner Landbrot":"a bakery loaf",
 "Kommissbrot":"a ration loaf","Mischbrot":"a bakery loaf",
 "Holzofenbrot":"a bakery loaf","Ruchbrot":"a bakery loaf",
 "Hubertus bread":"a bakery loaf","K-brot":"a bakery loaf",
 "Palabirabrot":"a fruit loaf","Einback":"a bakery item",
 "Butterbrot":"a slice with butter on it, a dish","Cemita":"a sandwich",
 "Acemita tocuyana":"a regional loaf","pan dulce":"a sweet bakery category",
 "Pan camaleón":"a regional loaf","Pan de Cruz":"a regional loaf",
 "Pan Sobado de La Rioja":"a regional loaf","Pan de cañada":"a regional loaf",
 "pan de coco":"a filled sweet roll","Pani Popo":"a coconut-sauced bun dish",
 "Saladilla":"a regional flatbread","Ochío":"a regional flatbread",
 "regañao":"a topped flatbread dish","Bisalto":"a regional bread",
 "Harinosas":"a regional bread","Panino":"a filled roll, a sandwich",
 "Panfocaccia":"a bakery item","Focaccia novese":"a regional focaccia",
 "fougasse":"a shaped bakery loaf","pompe à l'huile":"a festival sweet bread",
 "pain à la grecque":"a sweet bakery item","Faluche":"a regional roll",
 "pain brié":"a regional loaf","pain de campagne":"a regional loaf",
 "flûte":"a bakery loaf","boule":"a bakery loaf shape","Boule de pain":"a bakery loaf shape",
 "cottage loaf":"a bakery loaf shape","plain loaf":"a bakery loaf shape",
 "pan loaf":"a bakery loaf shape","Filone":"a bakery loaf shape",
 "baton":"a bakery loaf shape","Daktyla":"a regional loaf",
 "lagana":"a festival flatbread","Somun":"a regional flatbread",
 "somun":"a regional flatbread","Ramadan pide":"a festival flatbread",
 "Açma":"a bakery ring","zeytinli açma":"a bakery ring","poğaça":"a filled bakery bun",
 "Tepertős pogácsa":"a filled savoury scone","Belokranjska pogača":"a festival flatbread",
 "szpekuchy":"a topped flatbread dish","żulik":"a regional roll",
 "Korzh":"a regional flatbread","palianytsia":"a regional loaf",
 "psatyr":"a regional flatbread","Kilor":"a regional flatbread",
 "kömech":"a regional bread","Patîle":"a regional flatbread",
 "Gijda":"a regional flatbread","Sepik":"a regional flatbread",
 "Tapalapa":"a regional bread","agege":"a regional loaf",
 "Ngome":"a regional flatbread","Aghroum":"a regional flatbread",
 "Kesra":"a regional flatbread","Matlou":"a regional flatbread",
 "Khobz el-dâr":"a regional loaf","Sabaayad":"a layered flatbread dish",
 "Himbasha":"a festival bread","Kitcha":"a griddle bread dish",
 "kocho":"a fermented enset bread dish","dombolo":"a steamed dumpling bread dish",
 "braai bread":"a grilled bread dish","Potbrood":"a pot-baked bread dish",
 "bammy":"a cassava flatbread dish","cazabe":"a cassava flatbread",
 "fermented cassava bread":"a cassava flatbread","cassava starch bread":"a cassava flatbread",
 "coco bread":"a filled roll","hard dough bread":"a regional loaf",
 "peg bread":"a regional loaf","Succarie bread":"a regional loaf",
 "Rewena bread":"a regional loaf","Faraoa 'ipo":"a regional bread dish",
 "Laup":"a regional bread dish","Piki":"a paper-thin griddle bread dish",
 "Johnnycake":"a griddle cake dish","cornbread":"a baked side dish",
 "Boston brown bread":"a steamed loaf dish","Anadama bread":"a regional loaf",
 "salt-rising bread":"a regional loaf","San Francisco sourdough":"a regional loaf",
 "Scali bread":"a regional loaf","Limpa bread":"a regional loaf",
 "Jewish rye bread":"a regional loaf","Borodinsky bread":"a regional loaf",
 "black bread":"a regional loaf category","brown bread":"a loaf category",
 "Graham bread":"a named formula loaf","Tiger bread":"a topped loaf",
 "crackling bread":"a regional loaf","horsebread":"a historical loaf",
 "Oberlander":"a regional loaf","Szczecin bread":"a regional loaf",
 "Houska":"a festival plait","vrtanek":"a festival ring bread",
 "Podpłomyk":"a griddle flatbread","Mlinci":"a dried flatbread dish",
 "Ajdov Kruh":"a regional loaf","Daujenu namine duona":"a regional loaf",
 "Kovaohranen":"a regional loaf","Strutar":"a regional loaf",
 "Upplandskubb":"a steamed loaf dish","Hönökaka":"a regional flatbread",
 "halvtjockkakor":"a regional flatbread","mjukkaka":"a regional flatbread",
 "tunnbröd":"a regional flatbread","Flatbrød":"a regional crispbread",
 "Flatkaka":"a regional flatbread","Laufabrauð":"a festival fried bread",
 "Rúgbrauð":"a geothermal-baked loaf dish","kavring":"a regional loaf",
 "paltbröd":"a blood-bread dish","Syrat bröd":"a regional loaf",
 "Soft Bröd":"a regional flatbread","blöta":"a dipped-bread dish",
 "skjenning":"a regional flatbread","ankerstokk":"a fruit loaf",
 "krydder":"a spiced bun","kindermanstik":"a festival figural bread",
 "Kneippbrød":"a named formula loaf","fullkornsbröd":"a loaf category",
 "Vierreleipä":"a regional flatbread","reikäleipä":"a regional ring loaf",
 "Ruisrevitty":"a regional loaf","Vuokaleipä":"a tin loaf",
 "Kateleipä":"a regional flatbread","Kylvöleipä":"a ritual loaf",
 "Joutsenon rieska":"a regional flatbread","rieska":"a regional flatbread",
 "rievä":"a regional flatbread","Rasvarieska":"a regional flatbread",
 "jälkiuunileipä":"a regional loaf","limppu":"a regional loaf",
 "sekaleipä":"a loaf category","Puikula":"a regional loaf",
 "Hollolan näkkileipä":"a regional crispbread","silkko":"a regional loaf",
 "kakko":"a filled loaf dish","kalakukko":"a fish-filled loaf dish",
 "kampsu":"a filled pasty","Sochen'":"a griddle bread dish",
 "Korzh ":"a regional flatbread","Pashti":"a regional bread",
 "Tonis puri":"a tandoor loaf","Shoti":"a tandoor loaf",
 "Mchadi":"a griddle corn bread dish","Samoon":"a tandoor loaf",
 "Samarkand non":"a tandoor loaf","tandyr nan":"a tandoor loaf",
 "Taftan":"a tandoor loaf","Sangak":"a tandoor flatbread",
 "Barbari bread":"a tandoor flatbread","Aish baladi":"a regional flatbread",
 "aish merahrah":"a regional flatbread","eish fino":"a regional roll",
 "taboon bread":"a regional flatbread","saj bread":"a regional flatbread",
 "Laffa":"a regional flatbread","markook":"a regional flatbread",
 "manakish":"a topped flatbread dish","Kulcha":"a regional flatbread",
 "Katlam ":"a layered fried bread","Patir":"a regional flatbread",
 "Baati":"a baked dough ball dish","bhakri":"a griddle flatbread",
 "makki ki roti":"a griddle flatbread","Chapati":"a griddle flatbread",
 "chapati":"a griddle flatbread","kisra":"a regional flatbread",
 "injera":"a fermented griddle flatbread","talo":"a griddle corn cake",
 "gáhkku":"a regional flatbread","lefse":"a regional flatbread",
 "Beschuit":"a rusk product","Paximathia":"a rusk product",
 "friselle":"a rusk product","Schuettelbrot":"a crispbread",
 "Vinschgauer":"a regional flatbread","Vinschgauer struzn PAT":"a regional flatbread",
 "Coppia Ferrarese PGI":"a regional bread","Pane di Altamura PDO":"a regional loaf",
 "Pane casareccio di Genzano PGI":"a regional loaf","Pane di Matera PGI":"a regional loaf",
 "Pane nero di Castelvetrano":"a regional loaf","Pane carasau":"a regional crispbread",
 "civraxiu":"a regional loaf","pane ticinese":"a regional loaf",
 "Chiabattini":"a bakery roll","corone":"a bakery loaf shape",
 "Bread of Cea":"a regional loaf","Broa":"a regional corn loaf",
 "Veka":"a regional loaf","pa de pagès":"a regional loaf",
 "pa de pages catala":"a regional loaf","pa de ronyó":"a regional loaf",
 "pan candeal":"a regional loaf","Ekmek":"a regional loaf",
 "Açık ekmek":"a regional loaf","Vakfıkebir ekmeği":"a regional loaf",
 "Regeringsbrood":"a named formula loaf","Whole wheat spaghetti":"a variant page",
 "Kaak ":"a ring bread","marquesote":"a regional cake",
 "Guagua":"a figural festival bread","nokul":"a filled sweet roll",
 "Kaomianjin ":"a gluten dish","jampan":"a filled bun",
 "pulppang":"a filled bun","huintteok-guksu":"a noodle dish",
 "Alur":"a fried snack","wafer cookie":"a confection",
 "Bolo":"a regional cake","Trivandrum":"a filled sweet",
 "gembukan":"a steamed bun dish","baozi":"a filled steamed bun, a dish",
 "nikuman":"a filled steamed bun, a dish","Ampas Tarigu":"a bakery by-product dish",
 "Caramanduca ":"a regional sweet","Alur papad ":"a fried snack",
 "Cachitos ":"a filled roll","hot dog":"a sandwich",
}

# ── BORDERLINE: sold dry or frozen AND served as a dish ──────────────────────
BORDER = {
 # filled pasta and dumplings: a supermarket packet and a plated dish share the name
 "ravioli":"sold fresh and dried, also the plated dish","tortellini":"sold dried, also a dish",
 "tortelloni":"sold fresh, also a dish","cappelletti":"sold dried, also a dish",
 "cappellacci di zucca":"sold fresh, also a dish","Cappellacci di zucca ferraresi PGI":"a PGI product and a dish",
 "agnolotti":"sold fresh, also a dish","casoncelli":"sold fresh, also a dish",
 "culurgiones":"sold fresh, also a dish","pansotti":"sold fresh, also a dish",
 "fagottini":"sold fresh, also a dish","medaglioni":"sold fresh, also a dish",
 "sacchettoni":"sold fresh, also a dish","Sorrentinos":"sold fresh, also a dish",
 "Casunziei":"sold fresh, also a dish","raviole":"sold fresh, also a dish",
 "Tortelli":"sold fresh, also a dish","tortello amaro di Castel Goffredo":"a PGI product and a dish",
 "tortello della Possenta":"a regional product and a dish",
 "pierogi":"sold frozen, also a dish","varenyky":"sold frozen, also a dish",
 "pelmeni":"sold frozen, also a dish","uszka":"sold frozen, also a dish",
 "kreplach":"sold frozen, also a dish","manti":"sold frozen, also a dish",
 "mandu":"sold frozen, also a dish","jiaozi":"sold frozen, also a dish",
 "wonton":"sold frozen, also a dish","har gow":"sold frozen, also a dish",
 "shumai":"sold frozen, also a dish","bánh bột lọc":"sold frozen, also a dish",
 "lazanki":"sold dried, also a dish","gnocchi":"sold vacuum-packed, also a dish",
 "gnocchi di zucca":"sold fresh, also a dish","Gnudi":"a fresh dumpling, made not bought",
 "spätzle":"sold dried and fresh, also made to order","Passatelli":"made to order, also sold fresh",
 "pizzoccheri":"sold dried, also the named dish","malloreddus":"sold dried, also the named dish",
 "fregula":"sold dried, also the named dish","Ptitim":"sold dried, an Israeli product",
 "egg barley":"sold dried, a Hungarian product","Farfel ":"sold dried",
 "orzo":"sold dried","corzetti":"sold dried, stamped to order",
 "strascinati":"sold dried, also shaped to order","cavatelli":"sold dried and fresh",
 "Boraki ":"a dish","Crouzets ":"a regional product",
 # finished baked goods a recipe can legitimately call for by name
 "bagel":"bought as a product, and a finished baked good",
 "bialy":"bought as a product","English muffin":"bought as a product",
 "crumpet":"bought as a product","muffin":"bought as a product, also home-baked",
 "scone":"bought as a product, also home-baked","pancake":"a dish, also sold ready-made",
 "waffle":"a dish, also sold ready-made","brioche":"bought as a product",
 "challah":"bought as a product, and a ritual bread","bun":"a generic bakery format",
 "bread roll":"a generic bakery format","sandwich bread":"a supermarket format",
 "white bread":"a supermarket format","whole wheat bread":"a supermarket format",
 "rye bread":"a supermarket format","sourdough bread":"a supermarket format",
 "potato bread":"a supermarket format","soda bread":"home-baked, also sold",
 "barley bread":"a regional format","maize bread":"a regional format",
 "rice bread":"a regional format","chickpea bread":"a regional format",
 "corn tortilla":"a supermarket product, duplicates an existing row",
 "wheat tortilla":"a supermarket product, duplicates an existing row",
 "gluten-free bread":"a supermarket format","Gluten-free sliced bread":"a supermarket format",
 "Japanese milk bread":"a supermarket format","Vienna bread":"a bakery format",
 "french bread":"a bakery format","Mafalda":"a regional loaf sold whole",
 "ciabatta":"bought as a product","focaccia":"bought as a product, also a base",
 "pita":"bought as a product","khubz":"bought as a product","lavash":"bought as a product",
 "matzah":"bought as a product","crispbread":"bought as a product",
 "rusk":"bought as a product","pumpernickel":"bought as a product",
 "pretzel":"bought as a product","baguette":"bought as a product",
 "flatbread":"a format, bought as a product","corn tortillas":"a supermarket product",
 "naan":"bought as a product","roti":"griddled to order, also sold",
 "paratha":"griddled to order, also sold frozen","malawach":"sold frozen",
 "roti bolen":"a filled pastry, sold","roti gambang":"a regional loaf, sold",
 "kuih":"a sweet category","Bolo de Milho":"a regional cake",
 "sōmen":"sold dried","Hiyamugi":"sold dried","kishimen":"sold dried",
 "Miki":"sold fresh, also the named dish","Misua":"sold dried",
 "bakmi":"sold dried, also the named dish","Soun":"sold dried",
 "Mixian":"sold fresh, also the named dish","bánh canh":"sold fresh, also a dish",
 "bánh hỏi":"sold fresh, also a dish","Mì":"a generic Vietnamese noodle word",
 "yi mein":"sold dried, also the named dish","lamian":"pulled to order, also sold",
 "biangbiang noodles":"pulled to order, also the named dish",
 "dragon beard noodles":"pulled to order, a confection",
 "shirataki noodles":"sold wet-packed","harusame noodles":"sold dried",
 "cellophane noodles":"sold dried","bean vermicelli":"sold dried",
 "Mung bean sheets":"sold dried","starch noodle":"sold dried",
 "sagu noodle":"sold dried","shahe fen":"sold fresh","lai fun":"sold fresh",
 "juanfen":"sold fresh","Hainanfen":"sold fresh","cumian":"sold fresh",
 "oil noodles":"sold fresh","Jook-sing noodles":"made to order, also sold",
 "Chencun noodles":"sold fresh","kesme":"cut to order, also sold dried",
 "buckwheat noodles":"sold dried","egg noodle":"sold dried",
 "dried noodle":"sold dried","rice noodle":"sold dried","cold rice noodles":"sold fresh",
 "wonton noodles":"sold fresh","Hakata udon":"sold fresh, also the named dish",
 "Sanuki udon":"sold fresh, also the named dish","ippon udon":"a regional dish",
 "Okinawa soba":"sold fresh, also the named dish","Goshiki somen":"sold dried",
 "Miwa somen":"sold dried","Shōdoshima sōmen":"sold dried","shima sōmen":"sold dried",
 "silver needle noodles":"sold fresh","Kuksu":"a dish, also the noodle",
 "pancit bihon":"sold dried, also the named dish","pancit canton":"sold dried, also the named dish",
 "pancit miki":"sold fresh, also the named dish","pancit sotanghon":"sold dried, also the named dish",
 "Kuaichap":"sold fresh, also the named dish","koro":"a regional noodle",
 "Migan":"a regional noodle","Yamin":"a regional noodle dish",
 "Tijian":"a regional noodle","Hele":"a regional noodle",
 "Rokube":"a regional noodle","chanrā":"a regional noodle",
 "fushimen":"a regional noodle","taimen":"a regional noodle",
 "ì-mī":"sold fresh, also the named dish","Mi bancir":"a regional noodle dish",
 "Kaak bread":"a ring bread","laghman":"pulled to order, also the named dish",
}

import re
# ── ⚠️ THE VERDICT IS READ BACK OFF THE REASON, NOT ASSIGNED SEPARATELY ──────
#    The first pass put every named regional loaf under DISH, which is wrong. A loaf you
#    buy from a baker is a thing a recipe line can name. A dish is the OUTPUT of cooking.
#    The operational test, stated so it can be disagreed with:
#      could an ingredient line name this as something you HAVE before you start cooking?
#    Mapping the reason to the verdict keeps the per-item judgment and fixes the axis in
#    one place. Longest matching key wins.
REASON_VERDICT = [
 # ── things that are not items at all ──
 ("product-code string","NOT-AN-ITEM"), ("metaclass","NOT-AN-ITEM"),
 ("category article","NOT-AN-ITEM"), ("category page","NOT-AN-ITEM"),
 ("a BRAND","NOT-AN-ITEM"), ("a PROCESS","NOT-AN-ITEM"),
 ("cultural-heritage","NOT-AN-ITEM"), ("a religious object","NOT-AN-ITEM"),
 ("a religious rite","NOT-AN-ITEM"), ("ritual meal offering","NOT-AN-ITEM"),
 ("a folklore CATEGORY","NOT-AN-ITEM"), ("a divination custom","NOT-AN-ITEM"),
 ("known only from tablets","NOT-AN-ITEM"), ("historical","NOT-AN-ITEM"),
 ("a WWII ration spec","NOT-AN-ITEM"), ("a named 1940s recipe","NOT-AN-ITEM"),
 ("named institutional formula","NOT-AN-ITEM"), ("a named formula, not a product","NOT-AN-ITEM"),
 ("a competition title","NOT-AN-ITEM"), ("research prototype","NOT-AN-ITEM"),
 ("not a food","NOT-AN-ITEM"), ("the wrong sense entirely","NOT-AN-ITEM"),
 ("a Dutch category","NOT-AN-ITEM"), ("a serving format","NOT-AN-ITEM"),
 ("a MEAL CATEGORY","NOT-AN-ITEM"), ("duplicate of the existing","NOT-AN-ITEM"),
 ("WASTE stream","NOT-AN-ITEM"), ("a sweet bakery category","NOT-AN-ITEM"),
 ("a loaf category","NOT-AN-ITEM"), ("a sweet category","NOT-AN-ITEM"),
 ("a bakery by-product","NOT-AN-ITEM"), ("an oven-method page","NOT-AN-ITEM"),
 ("a generic Vietnamese noodle word","NOT-AN-ITEM"),
 ("an emergency ration","NOT-AN-ITEM"), ("a ration loaf","NOT-AN-ITEM"),
 # ── cooked and plated ──
 ("dish","DISH"), ("a sandwich","DISH"), ("a finished sandwich","DISH"),
 ("named for the sandwich","DISH"), ("a cooked dish","DISH"),
 ("a preparation","DISH"), ("a fried appetizer","DISH"),
 ("a fried turnover","DISH"), ("a filled baked turnover","DISH"),
 ("a fried snack","DISH"), ("a baked snack","DISH"), ("a twice-baked snack","DISH"),
 ("a toasted snack","DISH"), ("a bar snack","DISH"),
 ("a soup garnish preparation","DISH"), ("a novelty dish","DISH"),
 ("a fried sweet","DISH"), ("a steamed sweet","DISH"), ("a sweet dish","DISH"),
 ("a skewered sweet","DISH"), ("a fried ring sweet","DISH"),
 ("a filled griddle sweet","DISH"), ("a topped sweet bun","DISH"),
 ("a fried filled sweet","DISH"), ("a filled fried roll","DISH"),
 ("a filled roll","DISH"), ("a split roll for filling","DISH"),
 ("a filled steamed bun","DISH"), ("a filled bun","DISH"),
 ("a filled pasty","DISH"), ("a filled meat pie","DISH"),
 ("a filled crisp pancake","DISH"), ("a fried cheese stick","DISH"),
 ("a cheese roll","DISH"), ("a cheese-dough roll","DISH"),
 ("a filled loaf","DISH"), ("a topped loaf","DISH"), ("a topped flatbread","DISH"),
 ("a fried ring","DISH"), ("a pull-apart sweet","DISH"), ("a fried dough","DISH"),
 ("a fried bread","DISH"), ("a fried-bread","DISH"), ("a fried corn stick","DISH"),
 ("a fried ring bread","DISH"), ("a layered fried bread","DISH"),
 ("a stuffed griddle bread","DISH"), ("a griddle bread","DISH"),
 ("a griddle flatbread","DISH"), ("a griddle cake","DISH"),
 ("a griddle corn","DISH"), ("a fresh-corn griddle cake","DISH"),
 ("a baked layered bread","DISH"), ("a grilled gluten","DISH"),
 ("a paper-thin griddle bread","DISH"), ("a baked side dish","DISH"),
 ("a steamed loaf","DISH"), ("a steamed dumpling bread","DISH"),
 ("a steamed rice cake","DISH"), ("a steamed corn","DISH"),
 ("a steamed tamale","DISH"), ("a steamed stuffed bread","DISH"),
 ("a pot-baked bread","DISH"), ("a geothermal-baked loaf","DISH"),
 ("a torn-bread","DISH"), ("a dipped-bread","DISH"), ("a blood-bread","DISH"),
 ("a campfire dish","DISH"), ("an ember-baked","DISH"),
 ("a fermented enset bread","DISH"), ("a fermented maize dumpling","DISH"),
 ("a mashed dish","DISH"), ("a ritual grain dish","DISH"),
 ("a funeral rite","DISH"), ("a coconut-sauced bun","DISH"),
 ("a ritual soup","DISH"), ("a wonton soup","DISH"), ("a noodle soup","DISH"),
 ("a sweet egg-thread confection","DISH"), ("a syrup dessert","DISH"),
 ("a stuffed dessert","DISH"), ("a confection","DISH"),
 ("a meringue confection","DISH"), ("a sweet potato-dough","DISH"),
 ("spiralized courgette","DISH"), ("a slice with butter on it","DISH"),
 ("an overnight baked dish","DISH"), ("a filled sweet flatbread","DISH"),
 ("a filled savoury pastry","DISH"), ("a filled savoury bun","DISH"),
 ("a French pastry","DISH"), ("a layered pastry","DISH"),
 ("a filled pastry","DISH"), ("a filled bakery item","DISH"),
 ("a home-baked","DISH"), ("a named recipe","DISH"),
 ("a filled sweet plait","DISH"), ("a filled sweet loaf","DISH"),
 ("a filled ring cake","DISH"), ("a filled sweet bun","DISH"),
 ("a filled sweet","DISH"), ("a shaped sweet bread","DISH"),
 ("a filled fried doughnut","DISH"), ("a filled griddle cake","DISH"),
 ("a dried flatbread dish","DISH"), ("a dough ball","DISH"),
 ("a filled turnover","DISH"), ("a fried stuffed pastry","DISH"),
 ("a fried Mongolian turnover","DISH"), ("a fried Armenian dumpling","DISH"),
 ("a steamed Taiwanese dumpling","DISH"), ("a filled dumpling","DISH"),
 ("a composed dish","DISH"), ("a fresh dish","DISH"),
 ("a gluten dish","DISH"), ("a novelty filled bun","DISH"),
 ("a novelty sandwich","DISH"), ("the row is the whole burger","DISH"),
 ("the row is the assembled item","DISH"),
 ("a fresh dumpling, made not bought","DISH"),
 # ── bakery products a line can name ──
 ("a bakery roll","DRY-GOOD"), ("a bakery loaf shape","DRY-GOOD"),
 ("a bakery loaf","DRY-GOOD"), ("a bakery plait","DRY-GOOD"),
 ("a bakery ring","DRY-GOOD"), ("a bakery item","DRY-GOOD"),
 ("a bakery format","DRY-GOOD"), ("a finished bakery","DRY-GOOD"),
 ("a regional loaf","DRY-GOOD"), ("a regional roll","DRY-GOOD"),
 ("a regional bread","DRY-GOOD"), ("a regional corn loaf","DRY-GOOD"),
 ("a regional flatbread","DRY-GOOD"), ("a regional crispbread","DRY-GOOD"),
 ("a regional cake","DRY-GOOD"), ("a regional sweet bread","DRY-GOOD"),
 ("a regional sweet","DRY-GOOD"), ("a regional focaccia","DRY-GOOD"),
 ("a regional ring loaf","DRY-GOOD"), ("a regional product","DRY-GOOD"),
 ("a regional noodle","DRY-GOOD"), ("a tandoor loaf","DRY-GOOD"),
 ("a tandoor flatbread","DRY-GOOD"), ("a rusk product","DRY-GOOD"),
 ("a crispbread","DRY-GOOD"), ("a ring bread","DRY-GOOD"),
 ("a street-food ring bread","DRY-GOOD"), ("a fruit loaf","DRY-GOOD"),
 ("a tea loaf","DRY-GOOD"), ("a spiced bun","DRY-GOOD"),
 ("a sweet bun","DRY-GOOD"), ("a sweet plait","DRY-GOOD"),
 ("a sweet bakery item","DRY-GOOD"), ("a hard biscuit","DRY-GOOD"),
 ("a cassava flatbread","DRY-GOOD"), ("a fermented griddle flatbread","DRY-GOOD"),
 ("a festival cake","DRY-GOOD"), ("a festival bread","DRY-GOOD"),
 ("a festival loaf","DRY-GOOD"), ("a festival ring bread","DRY-GOOD"),
 ("a festival ring cake","DRY-GOOD"), ("a festival sweet bread","DRY-GOOD"),
 ("a festival bun","DRY-GOOD"), ("a festival plait","DRY-GOOD"),
 ("a festival fried bread","DRY-GOOD"), ("a festival figural bread","DRY-GOOD"),
 ("a figural festival bread","DRY-GOOD"), ("a wedding bread","DRY-GOOD"),
 ("an Easter bread","DRY-GOOD"), ("an Easter cake","DRY-GOOD"),
 ("a ritual loaf","DRY-GOOD"), ("a named formula loaf","DRY-GOOD"),
 ("a shaped bakery loaf","DRY-GOOD"), ("a tin loaf","DRY-GOOD"),
]
def _from_reason(reason):
    best=None
    for key,v in REASON_VERDICT:
        if key.casefold() in reason.casefold() and (best is None or len(key)>len(best[0])):
            best=(key,v)
    return best[1] if best else None

# ⚠️ PATTERN RULES. Only reach names the three tables missed. Each was read against the
#    residue it fires on. They are the weakest part of this judgment and are marked so in
#    the CSV's judged_by column.
PAT = [
 (r"\b(soup|salad|stew|hotpot|hot pot|burger|sandwich|casserole|pie)\b",
  "DISH","the name says it is a finished dish"),
 (r"^(fried|stir[- ]?fried|grilled|braised|steamed|boiled|baked|roasted|deep[- ]?fried|"
  r"hiyashi|bibim|cold|hot|ankake|yakisaba|chanpon)\b","DISH","the name opens with a cooking method"),
 (r"\b(mee|mie|guksu|myeon|mian|kway teow|laksa|japchae|yakisoba|champon|jjamppong|"
  r"tsukemen|somen|sōmen|udon|ramen|soba|pancit|dango|jiru|suanfen|noodles?)\b",
  "DISH","a named noodle DISH, the bowl and not the packet"),
 (r"(?:^|\s)(spaghetti|macaroni|vermicelli|pasta|penne|rigatoni|ziti|fusilli)\b",
  "DRY-GOOD","a dry pasta shape"),
]
# ── the residue the three tables and the reason map did not reach, read one by one ──
REST = {
 # 91 pasta shapes. Dry goods, all of them, and this is the clean half of the rule.
 **{k:("DRY-GOOD","a dry pasta shape") for k in (
  "acini di pepe","anelli","anellini","anelloni","barbine","bavette","bigoli","bucatini",
  "Busiate","caccavelle","Calamarata","Campanelle","cannelloni","capellini","capunti",
  "Casarecce","cascatelli","castellane","cavatappi","cencioni","ceppe","conchiglie",
  "conchigliette","conchiglioni","coquillette","Creste di gallo","ditalini","farfalle",
  "fazzoletti","fedelini","fettuccine","fileja","fiori","Foglie d'ulivo","fusillini",
  "garganelli","Gemelli","Girandole","lanterne","lasagne sheet","lasagnette","linguettine",
  "linguine","lumache","lumaconi","Maccheroncini di Campofilone PGI","mafaldine",
  "maltagliati","Manicotti","millerighe","occhi di lupo","orecchiette","paccheri",
  "pappardelle","pastina","pennoni","pici","pillus","pipe rigate","pljukanci","quadrefiore",
  "radiatori","riccioli","Romanitos","rombi","rotelle","rotini","sagnarelli","scialatelli",
  "sedani","Spighe","stelline","stortini","strichetti","stringozzi","strozzapreti",
  "tagliatelle","tagliolini","Torchio","tortiglioni","trenette","trenne","tripoline",
  "tripolini","troccoli","trofie","tuffoli","şehriye","макароны","рожки")},
 "מאזה מניקה":("NOT-AN-ITEM","a Hebrew label with no English reading in the corpus"),
 # 17 noodle residue. Dishes, all but one, and this is the dirty half of the rule.
 **{k:("DISH","a named noodle dish, the bowl and not the packet") for k in (
  "aburasoba","Bakmi Nyemek","Bun cha","Huo guo dun fen","kitsune","Mi bangka","Mi Gomak",
  "Mi Kocok","mi loncat","moriguksu","naengmyeon","pantruca","ranmen","Ranmian",
  "Singapore chow mein","tanuki","zhajiangmian")},
 # 48 bread residue
 "5 e 5":("DISH","a Bolivian filled-roll street dish"),
 "bannock":("DRY-GOOD","a griddle or oven bread, bought and baked"),
 "Batter bread":("NOT-AN-ITEM","metaclass, a dough-type class"),
 "bazeen":("DISH","a boiled barley dough served with stew"),
 "bazlama":("DRY-GOOD","a Turkish griddle flatbread, sold by bakers"),
 "bolus":("DRY-GOOD","a Surinamese sweet bakery roll"),
 "Cheesymite scroll":("DISH","a filled bakery item"),
 "Dalieba":("DRY-GOOD","a Harbin rye loaf, sold whole"),
 "Dalí bread":("NOT-AN-ITEM","an artwork, not a food"),
 "Farl":("DRY-GOOD","a quartered griddle bread, sold in packs"),
 "ftira":("DRY-GOOD","a Maltese ring loaf, sold whole"),
 "Gluten-free bread":("NOT-AN-ITEM","metaclass, a dietary class not a bread"),
 "Hearth bread":("NOT-AN-ITEM","metaclass, a baking-method class"),
 "Hvedebrød":("DRY-GOOD","a Danish wheat loaf"),
 "Khanom bueang":("DISH","a filled crisp pancake dish"),
 "kolmbeng":("DRY-GOOD","a Goan bakery roll"),
 "kompyang":("DRY-GOOD","a baked sesame roll, sold"),
 "Krol":("DRY-GOOD","a Dutch bakery roll"),
 "Matnakash":("DRY-GOOD","an Armenian oven flatbread, sold whole"),
 "Mekitsa":("DISH","a fried dough dish"),
 "no-knead bread":("NOT-AN-ITEM","a named method, not a product"),
 "Olive bread":("DRY-GOOD","a bakery loaf"),
 "Pan candeal":("DRY-GOOD","a regional loaf"),
 "Pan de yuca":("DISH","a cheese roll baked to order"),
 "parva":("NOT-AN-ITEM","a Czech word for a bread-crumb topping class"),
 "pide":("DRY-GOOD","a Turkish flatbread, sold whole"),
 "pihta":("DRY-GOOD","a Finnish flatbread"),
 "pitilla":("DRY-GOOD","a small flatbread, sold"),
 "poppy seed bun":("DRY-GOOD","a bakery roll"),
 "Pre-baked bread":("NOT-AN-ITEM","metaclass, a supply-chain class"),
 "pão francês":("DRY-GOOD","a Brazilian bakery roll"),
 "Rosca chonchina":("DRY-GOOD","a regional ring bread"),
 "rugbrød":("DRY-GOOD","a Danish rye loaf, sold sliced"),
 "rupjmaize":("DRY-GOOD","a Latvian rye loaf, sold whole"),
 "saldskābmaize":("DRY-GOOD","a Latvian sweet-sour rye loaf"),
 "schoten":("DRY-GOOD","a Frisian bakery loaf"),
 "setsuuri":("DRY-GOOD","a Japanese bakery item"),
 "Shio pan":("DRY-GOOD","a salt-butter roll, sold"),
 "straw bread":("NOT-AN-ITEM","a famine-food article, historical"),
 "taja":("DRY-GOOD","a Kashmiri bakery bread"),
 "tandoor bread":("NOT-AN-ITEM","metaclass, a baking-method class"),
 "tapan":("DRY-GOOD","a Central Asian flatbread"),
 "Telera":("DRY-GOOD","a Mexican bakery roll"),
 "viennoiserie":("NOT-AN-ITEM","a bakery CATEGORY, croissants and the rest"),
 "Wagafi bread":("DRY-GOOD","a regional loaf"),
 "ِAbbas bread":("DRY-GOOD","a regional loaf"),
 "ṣa":("NOT-AN-ITEM","an ancient Egyptian bread-loaf hieroglyph"),
 "パインぱん":("DRY-GOOD","a Japanese pineapple bun, sold"),
}
_NOT   = {k.casefold():v for k,v in NOT_ITEM.items()}
_DISH  = {k.casefold():v for k,v in DISH.items()}
_BORD  = {k.casefold():v for k,v in BORDER.items()}
_REST  = {k.casefold():v for k,v in REST.items()}
def judge(name):
    f=name.casefold()
    if f in _NOT:  return "NOT-AN-ITEM", _NOT[f], "hand"
    if f in _DISH: r=_DISH[f]; return (_from_reason(r) or "DISH"), r, "hand"
    if f in _BORD: return "BORDERLINE", _BORD[f], "hand"
    if f in _REST: return _REST[f][0], _REST[f][1], "hand"
    for rx,v,w in PAT:
        if re.search(rx,name,re.I): return v,w,"pattern"
    return None,None,None

# ── added for the Q2625877 pass: names the pasta-only branch reaches ─────────
REST.update({
 "gramigna":("DRY-GOOD","a dry pasta shape"),
 "chestnut tagliatelle":("DRY-GOOD","a flour-variant dry pasta, sold dried"),
 "colțunași":("BORDERLINE","sold frozen, also a made dish"),
 "pumpkin tortelli":("BORDERLINE","sold fresh, also a dish"),
 "tortelli alla piacentina":("BORDERLINE","sold fresh, also a regional dish"),
 "tortelli di patate":("BORDERLINE","sold fresh, also a dish"),
 "tortellini di Valeggio sul Mincio":("BORDERLINE","a PAT product, sold fresh"),
 "beef ravioli":("BORDERLINE","sold tinned and fresh, also a dish"),
 "bryndzové pirohy":("BORDERLINE","sold frozen, also a made dish"),
 "Ruthenian pierogi":("BORDERLINE","sold frozen, also a made dish"),
 "tortellini filled with cheese":("NOT-AN-ITEM","a DESCRIPTION, not a name a line uses"),
})
_REST.update({k.casefold():v for k,v in REST.items()})
