# -*- coding: utf-8 -*-
"""The 174 moved rows, judged one pattern at a time. Keyed (old phrase, old rows, new phrase, new rows)."""
F="the line names it FIRST; seg0 takes the main clause instead of a later alternative"
S="seg0 reaches the more specific name"
T="two ingredients are on one line by an import defect, so either row is defensible"
G="seg0 dropped to a generic or a non-food word"
J={
("black pepper","black pepper | peppercorn","sea salt","sea salt"):("BOTH-OK",T,""),
("chile powder","chili powder","red chile","chili pepper | Spaanse peper | New Mexico chile"):("WRONG","the ingredient is the POWDER, not the fresh pepper",""),
("kosher salt","kosher salt","cooking salt","table salt | kosher salt"):("BOTH-OK","'cooking salt / kosher salt' names both, and both rows are salt",""),
("lemon","lemon","juice","must | juice"):("WRONG","'must' is grape must; lemon was closer to 'juice of 1 lemon'",""),
("basil leaves","basil leaf","thai basil","Thai basil"):("RIGHT",S,""),
("olive oil","olive oil","ghee","animal fats and oils | ghee"):("RIGHT",F,""),
("cilantro","Coriandrum sativum | cilantro","coriander","coriander seed | Coriandrum sativum | cilantro"):("WRONG","the new set adds the coriander SEED row, a different ingredient from the leaf",""),
("cardamom pods","cardamom pod","green cardamom","cardamom"):("BOTH-OK","gains the green variety, loses the pod form","LOW"),
("black pepper","black pepper | peppercorn","kosher salt","kosher salt"):("BOTH-OK",T,""),
("greek yogurt","strained yogurt","whole milk","cow's milk | whole milk"):("WRONG","the ingredient is Greek yogurt; 'whole-milk' is its adjective",""),
("pepper","pepper","salt","salt"):("BOTH-OK",T,""),
("chilli powder","chili powder","red chilli","chili pepper | Spaanse peper"):("WRONG","the ingredient is the POWDER",""),
("chilies","chili pepper","-","-"):("WRONG","the language rule blocks 'chilies' (tagged Dutch) and nothing else on the line matches",""),
("avocado oil","avocado oil","oil","oil"):("RIGHT","the ingredient IS 'neutral oil'; avocado was the last of three examples",""),
("coffee powder","ground coffee | instant coffee","instant coffee","instant coffee"):("RIGHT","resolves the two-row set to the one the line names",""),
("cilantro","Coriandrum sativum | cilantro","parsley","parsley"):("RIGHT",F,""),
("chili flake","red pepper flakes","red chili","chili pepper | Spaanse peper"):("WRONG","the ingredient is the FLAKE",""),
("dried oregano","dried oregano","garlic powder","garlic powder"):("BOTH-OK","three spices on one line by an import defect",""),
("paprika","bell pepper | paprika","cumin","cumin"):("BOTH-OK","two spices on one line, and it drops the wrong bell-pepper row",""),
("canola oil","rapeseed oil | canola oil","vegetable","vegetable"):("WRONG","'vegetable' is the plant category, not vegetable oil",""),
("english cucumber","European cucumber","cucumbers","cucumber"):("RIGHT","Persian cucumbers is first-named, and plain cucumber beats European cucumber",""),
("chicken thighs","chicken thigh | chicken leg","bone","bone | diet"):("WRONG",G,""),
("chicken stock","broth | chicken broth","vegetable","vegetable"):("WRONG","'vegetable' is the plant category, not vegetable stock",""),
("chili powder","chili powder","chili flakes","red pepper flakes"):("RIGHT",F,""),
("lemon","lemon","zest","zest"):("WRONG","the generic zest row loses the lemon",""),
("orange","Orange","zest","zest"):("WRONG","the generic zest row loses the orange",""),
("corn kernels","corn kernel","frozen corn","frozen vegetable"):("WRONG","'frozen vegetable' is a storage category",""),
("corn kernels","corn kernel","ear","ear"):("WRONG",G,""),
("turkish white cheese","beyaz peynir","feta cheese","feta"):("RIGHT",F,""),
("chilli flakes","red pepper flakes","red peppers","red bell pepper | cayenne pepper"):("WRONG","the line is pul biber, and the new set leads with red BELL pepper",""),
("chillies","chili pepper","ancho","poblano"):("RIGHT","an ancho IS a dried poblano",""),
("water","water","chilli","chili pepper"):("WRONG","the ingredient is the chilli SOAKING WATER",""),
("oaxaca cheese","hebra cheese","colby","Colby cheese"):("RIGHT",F,""),
("hot sauce","chili sauce | hot sauce","salsa","sauce | salsa (food) | parsley | tomato salsa"):("BOTH-OK","salsa is first-named, but the new set drags in a parsley row","LOW"),
("ground turkey","ground turkey","ground meat","minced meat"):("BOTH-OK","'Ground meat / ground turkey' names both",""),
("vegetable oil","vegetable oil","ghee","animal fats and oils | ghee"):("RIGHT",F,""),
("jasmine rice","jasmine rice","grain","grain | grist | seed"):("WRONG","'grain' came out of 'short-grain'",""),
("vegetable stock","vegetable stock","water","water"):("RIGHT",F,""),
("cheddar","Cheddar cheese","cheese","cheese"):("RIGHT","the ingredient IS 'cheese'; cheddar is one of three examples",""),
("chicken breasts","chicken breast","boneless chicken","meat on the bone"):("WRONG","the line says BONELESS and the row says on the bone",""),
("onions","onion","shallots","shallot"):("RIGHT",F,""),
("monterey jack cheese","Monterey Jack","cheddar","Cheddar cheese"):("RIGHT",F,""),
("water","water","tomato","tomato"):("RIGHT","this line was a known wrong match under rightmost, and seg0 fixes it",""),
("escarole","broad-leaved endive | curly endive","spinach","spinach | Spinacia oleracea"):("RIGHT",F,""),
("chicken thighs","chicken thigh | chicken leg","boneless chicken","meat on the bone"):("WRONG","the line says BONELESS and the row says on the bone",""),
("tomato sauce","ketchup | tomato sauce","tomato puree","tomato purée"):("RIGHT",F+", and it drops the ketchup row",""),
("chili powder","chili powder","red chili","chili pepper | Spaanse peper"):("WRONG","the ingredient is the POWDER",""),
("coriander","coriander seed | Coriandrum sativum | cilantro","cilantro","Coriandrum sativum | cilantro"):("RIGHT","drops the seed row from a line about leaves",""),
("honey","honey","sugar","sugar"):("BOTH-OK","'Sugar / honey' names both",""),
("tea","tea","grey","grey"):("WRONG",G,""),
("rice","rice","chicken","chicken"):("BOTH-OK","'Chicken rice' is a dish name and neither row is the ingredient","LOW"),
("parsley","parsley","cilantro","Coriandrum sativum | cilantro"):("BOTH-OK","'Cilantro/Parsley' names both",""),
("vegetable oil","vegetable oil","sunflower","sunflower seed"):("WRONG","sunflower SEED is not sunflower oil",""),
("bread flour","Bread flour","white bread","baguette"):("WRONG","the ingredient is flour, and the row is a loaf",""),
("vegetable oil","vegetable oil","canola","rapeseed oil"):("RIGHT",F,""),
("palm sugar","palm sugar","brown sugar","brown sugar"):("RIGHT",F,""),
("spice blend","spice mix","tandoori masala","tandoori masala"):("RIGHT",S,""),
("cannellini beans","cannellini beans","white beans","white bean"):("RIGHT","the ingredient is 'white beans'; the rest of the line is examples",""),
("garlic","garlic | Allium sativum","clove","clove"):("WRONG","'clove' is the spice, not a garlic clove",""),
("great northern beans","white bean","cannellini","kidney bean | cannellini beans"):("BOTH-OK","cannellini is first-named, but the new set leads with red kidney bean","LOW"),
("white fish fillets","white fish fillets","snapper","snapper"):("RIGHT",F+" and "+S,""),
("english cucumber","European cucumber","cucumber","cucumber"):("RIGHT",F,""),
("green onions","Welsh onion | scallion","cilantro","Coriandrum sativum | cilantro"):("RIGHT",F,""),
("orange","Orange","juice","must | juice"):("WRONG","'must' is grape must",""),
("unsalted butter","unsalted butter","ghee","animal fats and oils | ghee"):("RIGHT",F,""),
("hot pepper flakes","red pepper flakes","korean hot pepper","Korean chili pepper"):("RIGHT",S+" (gochugaru)",""),
("vegetable stock","vegetable stock","chicken","chicken"):("WRONG","'chicken' the bird, not chicken stock",""),
("chili flakes","red pepper flakes","pepper","pepper"):("BOTH-OK","Aleppo pepper is first-named, and 'pepper' is coarse but not wrong","LOW"),
("lemons","lemon","zest","zest"):("WRONG","the generic zest row loses the lemon",""),
("chicken stock","broth | chicken broth","gluten","seitan"):("WRONG","'gluten' came out of 'gluten-free'",""),
("kosher salt","kosher salt","masa harina","masa"):("RIGHT","two ingredients on one line and masa harina is the first and the larger",""),
("canola oil","rapeseed oil | canola oil","bacon fat","bacon"):("RIGHT",F,""),
("lime","lime","juice","must | juice"):("WRONG","'must' is grape must",""),
("red wine","red wine","pinot noir","pinot noir"):("RIGHT",S,""),
("parsley","parsley","basil","basil"):("RIGHT",F,""),
("radish","radish","daikon","Japanese radish"):("RIGHT",S,""),
("basil","basil","cilantro","Coriandrum sativum | cilantro"):("RIGHT",F,""),
("provolone cheese","Provolone","mozzarella cheese","mozzarella cheese"):("RIGHT",F,""),
("yeast","yeast | Saccharomyces cerevisiae | raising agent","rise","rice"):("WRONG","'rise' came out of 'rapid-rise' and reached the rice row",""),
("chile","chili pepper","serrano","bolognese sauce | Serrano ham"):("WRONG","Serrano the chile reached Serrano HAM",""),
("clementine","Clementine fruit | Citrinos × clementina","peel","zest"):("WRONG","the ingredient is the clementine",""),
("vegetable oil","vegetable oil","oil","oil"):("RIGHT","the ingredient IS 'oil'; the bracket lists four examples",""),
("monterey jack","Monterey Jack","shredded cheese","grated cheese"):("RIGHT","the ingredient IS 'shredded cheese'; three cheeses follow as examples",""),
("parmigiano reggiano","Parmesan","pecorino","pecorino"):("RIGHT",F,""),
("shaoxing wine","Shaoxing wine","cooking wine","cooking alcohol"):("BOTH-OK","the parenthetical names it exactly, so the old row was tighter","LOW"),
("chicken thigh","chicken thigh | chicken leg","skin","skin"):("WRONG",G,""),
("crushed tomatoes","mashed tomatoes","tomato passata","tomato purée"):("RIGHT",F,""),
("sausages","Sausage","pork","pork"):("WRONG","the ingredient is sausages; pork is the adjective",""),
("microgreens","microgreen","sprouts","sprouting"):("WRONG","'sprouting' is the germination process",""),
("pumpkin","pumpkin","sugar","sugar"):("WRONG","'sugar pumpkin' is a variety name",""),
("flour","flour","ap","all-purpose flour"):("RIGHT","AP is all-purpose, so this is exact",""),
("vegetable oil","vegetable oil","coconut oil","Coconut oil | coconut oil"):("RIGHT",F,""),
("ground cloves","ground cloves","ground ginger","ground ginger"):("BOTH-OK",T,""),
("chili sauce","chili sauce | hot sauce","black bean","black turtle bean"):("WRONG","it is a bean SAUCE, not beans",""),
("swiss chard","Brassica rapa subsp. chinensis | chard","spinach","spinach | Spinacia oleracea"):("RIGHT",F,""),
("beef","beef","chicken","chicken"):("RIGHT",F,""),
("vegetable oil","vegetable oil","olive","olive"):("WRONG","'olive' the fruit, not olive oil",""),
("dough","dough","tahini","tahini"):("WRONG","the ingredient is the dough",""),
("douban jiang","doubanjiang","bean paste","bean paste"):("BOTH-OK","same thing, one grain coarser",""),
("cinnamon stick","cinnamon stick","chinese cinnamon","cassia"):("RIGHT","Chinese cinnamon IS cassia",""),
("red chile","chili pepper | Spaanse peper | New Mexico chile","white rice","white rice"):("RIGHT","the stored label and raw_text disagree on this line, and white rice fits the raw text",""),
("thai chili","bird's eye chili","birds eye","piri piri"):("BOTH-OK","birds eye is first-named and piri piri is one of its varieties","LOW"),
("leafy green","leaf vegetable","kale","kale"):("RIGHT",F,""),
}
