# -*- coding: utf-8 -*-
"""Reason for each of the 42 lines the NEW matcher leaves with nothing, keyed by raw_text.
   Every REAL-GAP below was PROVEN by probing the 183,651-key index for the name."""
G="REAL-GAP"; NI="NOT-INGREDIENT"; H="HEAD-NOT-IN-INDEX"; DS="DECLINED-STOPWORD"
R={
"600g/ 1.2lb zucchinis (4 large, 5 medium)":(H,"'zucchini' IS an index key, 'zucchinis' is not: depluralize's ss/us/is guard blocks any plural whose singular ends in i","zucchini"),
"2 tablespoons (30 ml) bourbon":(G,"probed: 'bourbon' is not among the 183,651 index keys","bourbon"),
"1 tsp tumeric powder":(H,"'turmeric' IS an index key, the line misspells it 'tumeric'","turmeric"),
"1¼ cups plus 2 tablespoons":(NI,"a quantity fragment, the import split one line into two",""),
"(160 ml, warmed)":(NI,"a quantity fragment with no name",""),
"(thinly sliced)":(NI,"a prep note with no name",""),
"½ teaspoon MSG (optional)":(G,"probed: neither 'msg' nor 'monosodium glutamate' is an index key","MSG"),
"Optional":(NI,"a bare word, no ingredient",""),
"¼ teaspoon freshly ground black":(NI,"truncated by the import, the word 'pepper' is missing",""),
"⅛ teaspoon freshly ground black":(NI,"truncated by the import, the word 'pepper' is missing",""),
"(450g, medium thickness)":(NI,"a quantity fragment with no name",""),
"Chilis":(H,"'chili' IS an index key, 'chilis' is not: the same depluralize guard","chili"),
"Paratha":(G,"probed: 'paratha' is not an index key","paratha"),
"1 eschalot , small, finely chopped (~1 1/2 tbs)":(G,"'shallot' IS a row, but 'eschalot' is not one of its names","eschalot (a name for shallot)"),
"Ice, for serving":(DS,"'ice' is the only index key on the line and my stoplist blocks it; the key also reaches an ice cream row, not plain ice",""),
"1 (4 ounce) can green chilis":(H,"'chili' IS an index key, 'chilis' is not: the same depluralize guard","chili"),
"(224 grams), plus more for dusting":(NI,"a quantity fragment with no name",""),
"sifted":(NI,"a prep word alone on a line",""),
"4 teaspoon freshly ground black":(NI,"truncated by the import, the word 'pepper' is missing",""),
"1 tsp (4g) MSG, divided":(G,"probed: neither 'msg' nor 'monosodium glutamate' is an index key","MSG"),
"Ditalini, about 1/4 per person":(G,"probed: 'ditalini' is not an index key, though penne, spaghetti, linguine and lasagne all are","ditalini"),
"2 cups ice":(DS,"'ice' is the only index key on the line and my stoplist blocks it; the key also reaches an ice cream row, not plain ice",""),
"(384 grams)":(NI,"a quantity fragment with no name",""),
"Nonstick spray":(G,"'cooking spray' IS an index key, 'nonstick spray' is not","nonstick spray"),
"A pinch roasted kasuri methi powder":(G,"'fenugreek' IS a row, but kasuri methi is the dried leaf and has no key","kasuri methi"),
"1/2 Lb Rigatoni":(G,"probed: 'rigatoni' is not an index key","rigatoni"),
"1 1/2 Cups of Felicetti Ditalini":(G,"probed: 'ditalini' is not an index key","ditalini"),
"1 lb of Tubetti":(G,"probed: 'tubetti' is not an index key","tubetti"),
"1/2 Cup Parm for garnish":(H,"'parmesan' IS an index key, the abbreviation 'Parm' is not","parmesan"),
"bagels":(G,"probed: neither 'bagel' nor 'bagels' is an index key","bagel"),
"(This makes more than you need, but you can freeze the rest)":(NI,"a storage note",""),
"1 lb Rigatoni":(G,"probed: 'rigatoni' is not an index key","rigatoni"),
"New adds":(NI,"a heading the import did not flag as one",""),
"(sliced into ½-inch thick rectangles; about 1½ x 2 inches)":(NI,"a prep note with no name",""),
"1/4 teaspoon MSG":(G,"probed: neither 'msg' nor 'monosodium glutamate' is an index key","MSG"),
"1/2 lb of Felicetti Rigati":(G,"probed: 'rigati' is not an index key","rigati"),
"1-3 fresh or dried red chilis":(H,"'chili' IS an index key, 'chilis' is not: the same depluralize guard","chili"),
"1 Lb of Mezze Rigatoni":(G,"probed: neither 'mezze rigatoni' nor 'rigatoni' is an index key","mezze rigatoni"),
"Lu Bao herb packet":(G,"probed: no key for lu bao or for a herb packet","lu bao herb packet"),
"cleaned and cut in half crosswise":(NI,"a prep note with no name",""),
"powder":(NI,"a bare word, the import split one line into two",""),
}
