# -*- coding: utf-8 -*-
"""Verdicts on the 98 read redirect names. X=CROSS-CONCEPT, L=LEGIT-ALIAS, B=BORDERLINE."""
X="CROSS-CONCEPT"; L="LEGIT-ALIAS"; B="BORDERLINE"
FIRING = {
 "Bay leaves":(L,"plural of the canonical"), "Bay Leaves":(L,"plural of the canonical"),
 "Bean sauce":(B,"tianmianjiang IS sweet bean sauce, but bare 'bean sauce' also names doubanjiang"),
 "Beef stock":(B,"lands on generic 'broth' and loses the beef, while a beef broth row exists"),
 "Bread crumbs":(L,"spacing variant"), "Butter milk":(L,"spacing variant"),
 "Cake":(X,"⚠ the bare word 'cake' as an ARTICLE TITLE on the Jaffa Cakes row"),
 "Chicken stock":(B,"lands on generic 'broth' and loses the chicken"),
 "Coffee powder":(L,"instant coffee is sold as a powder"),
 "Feta (cheese)":(L,"disambiguated title"), "Feta cheese":(L,"the cheese word is redundant, not new"),
 "Flour tortillas":(L,"plural of wheat tortilla"),
 "Jack (cheese)":(L,"disambiguated title"), "Jack cheese":(L,"short form"),
 "Kaffir Lime Leaves":(L,"plural"), "Lime leaves":(L,"plural"),
 "Malted milk powder":(L,"malted milk is sold as a powder"),
 "Mango powder":(L,"amchoor IS dried mango powder"),
 "Miso paste":(L,"miso is a paste, the word adds nothing"),
 "Monterey Jack Cheese":(L,"redundant cheese word"), "Monterey jack cheese":(L,"redundant cheese word"),
 "Monterey Jack cheese":(L,"redundant cheese word"),
 "Muscovado sugar":(L,"muscovado IS a sugar"),
 "Parmesan (cheese)":(L,"disambiguated title"), "Parmesan cheese":(L,"redundant cheese word"),
 "Parmesan Cheese":(L,"redundant cheese word"),
 "Pasta water":(X,"⚠ the starchy cooking liquid, not pasta. FIRES on 'Salted Pasta Water'"),
 "Pecorino cheese":(B,"generic pecorino lands on the Pecorino Romano PDO row specifically"),
 "Pecorino Romano cheese":(L,"redundant cheese word"),
 "Piri-piri sauce":(X,"⚠ the row is the CHILI PEPPER. FIRES on '1 cup Piri Piri Sauce'"),
 "Provolone (cheese)":(L,"disambiguated title"), "Provolone cheese":(L,"redundant cheese word"),
 "Rice powder":(L,"rice flour and rice powder are the same product"),
 "Semolina flour":(L,"semolina IS a flour"),
 "Soup":(X,"⚠ the bare word 'soup' as an ARTICLE TITLE on the broth row. A dish, not an ingredient"),
 "Sourdough bread":(L,"sourdough names the bread"), "Spice blend":(L,"synonym of spice mix"),
 "Sweet bean sauce":(L,"tianmianjiang IS sweet bean sauce"),
}
LATENT = {
 "Achiote paste":(L,"recado rojo IS achiote paste"), "Amchur powder":(L,"amchoor is the powder"),
 "Bat stew":(X,"a stew is not the meat"), "Bee-bread":(B,"bee bread is fermented pollen, close but not pollen"),
 "Beer batter":(B,"a specific batter landing on the generic batter row"),
 "Beer battering":(B,"a PROCESS name on an ingredient row"),
 "Birch water":(L,"birch sap is sold as birch water"),
 "Breadcrumb sauce":(B,"lechon sauce does contain breadcrumbs, the naming is loose"),
 "Cake meal":(L,"cake meal is fine matzo meal"), "Cat-meat stew":(X,"a stew is not the meat"),
 "Chicken bouillon powder":(B,"powder and cube are different formats of the same product"),
 "Chili pepper paste":(B,"paste and sauce are different products, loosely named"),
 "Chutney powder":(X,"⚠ chutney podi is a DRY powder, a different thing from wet chutney"),
 "Cider in Germany":(L,"an article title, still names Apfelwein"),
 "Cock sauce":(L,"slang for the rooster-brand sriracha"),
 "Cotton seed oil":(L,"spacing variant"), "Date syrup":(L,"date honey IS date syrup"),
 "Dinner salad":(X,"⚠ a composed dish landing on the LETTUCE PLANT row"),
 "Egg-lemon soup":(X,"a soup is not the sauce"),
 "Flavored fortified wine":(L,"singular of the canonical"),
 "Garden Salad":(X,"⚠ a composed dish landing on the LETTUCE PLANT row"),
 "Hellim cheese":(L,"Turkish name for halloumi"), "Indian meal":(L,"archaic term for cornmeal"),
 "Kumquat liqueur":(X,"a liqueur is not the fruit"),
 "Livarot cheese":(L,"redundant cheese word"), "Liver cheese":(L,"English name for Leberkase"),
 "Machine separated pork":(B,"pork specifically, on a generic meat row"),
 "Malt powder":(B,"malt powder and malted milk powder are not always the same"),
 "Mascarpone cheese":(L,"redundant cheese word"), "Matcha tea":(L,"redundant tea word"),
 "Milk shakes":(L,"spacing and plural"), "Olive-leaf noodle":(L,"English name for the shape"),
 "Pancake mix":(X,"a dry mix is not a pancake"),
 "Peanut sauce":(L,"names the same sauce family"),
 "Pho soup":(X,"⚠ the SOUP landing on banh pho, the NOODLE"),
 "Pine seed":(L,"pine nut is a seed"), "Potato starch flour":(L,"the same product"),
 "Prune Cake":(B,"a specific cake on the fruitcake row"),
 "Pu'erh tea":(X,"⚠ A TEA LANDING ON 'egg as food'. Almost certainly routed through 'tea egg'"),
 "Puff paste":(L,"archaic name for puff pastry"), "Romesco sauce":(L,"redundant sauce word"),
 "Rum butter":(B,"brandy butter and rum butter differ by the spirit"),
 "Saint Nectaire cheese":(L,"redundant cheese word"), "Salad onion":(L,"British name for scallion"),
 "Seasoning mix":(L,"synonym of spice mix"), "Seasoning salt":(L,"variant of seasoned salt"),
 "Sherry wine":(L,"sherry IS a wine"), "Sugar scraper":(X,"⚠ a TOOL landing on the sugarloaf row"),
 "Sugar-free":(B,"an adjective, not an ingredient name"),
 "Sweet soy sauce":(L,"kecap manis IS sweet soy sauce"),
 "Swiss style cheese":(L,"names the same category"), "Tangerine peel":(L,"chenpi IS dried tangerine peel"),
 "Thai fish sauce":(L,"nam pla IS Thai fish sauce"),
 "Thieves oil":(X,"⚠ an OIL landing on four thieves VINEGAR"),
 "Thin coconut milk":(X,"⚠ thin coconut milk is the OPPOSITE end of the product from coconut cream"),
 "Tomato jelly":(B,"jelly and puree are different preparations"),
 "Tzatziki sauce":(L,"redundant sauce word"), "Yogurt cheese":(L,"yogurt cheese IS strained yogurt"),
 "Yogurt Ice-cream":(X,"frozen yogurt is not yogurt"),
 "Zucchini cake":(X,"⚠ a CAKE landing on the zucchini vegetable row"),
}
