# -*- coding: utf-8 -*-
"""NEW-ONLY verdicts, keyed (matched phrase, row names). Read one pattern at a time.
   Anything not listed here is NEW-RIGHT with no reservation."""
ALT="the line names another ingredient FIRST; longest-wins took the alternative because it has more words"
FORMW="the matched word names a shape or a preparation, not the ingredient on the line"
PAREN="the match came from a parenthetical note, not from what the line is asking for"
WRONG={
("dried yeast","nutritional yeast"):"nutritional yeast is a different product from baker's dried yeast",
("cubes","butter"):FORMW,
("pan","bread"):"'pan' here is the cookware; the row reached is pan bread",
("purée","purée"):FORMW+" (the line is onion, and pumpkin)",
("butter","butter | food paste"):"speculoos cookie butter is a spread, not butter",
("cai","cabbage"):"'cai' is a syllable of sui mi ya cai and of cai zi you, not a standalone word",
("chips","French fries"):"tortilla chips are not French fries",
("extract","extract"):"the generic extract row loses the vanilla and the almond",
("lime zest","lemon zest"):"lime zest routed onto the lemon zest row",
("maple syrup","maple syrup"):ALT,
("pasta water","pasta"):"pasta water is not pasta, and on the second line the ingredient is salt",
("pepe","peppercorn"):"'Pepe' is part of the pasta shape Acini di Pepe",
("puree","purée | mashed potato"):FORMW+" (the line is pumpkin puree)",
("rind","crust | beef"):"a Parmigiano rind is cheese, not crust and not beef",
("aromatic herb","essential oil"):"a lu bao herb packet is not an essential oil",
("baby spinach","baby spinach"):ALT+" (the ingredient is cilantro)",
("bean paste","bean paste"):"vanilla bean paste is not fermented bean paste",
("beef broth","beef broth"):ALT+" (vegetable broth is first)",
("black eyed peas","pinto bean"):"black-eyed peas are cowpeas, not pinto beans",
("bottom round","minced meat"):"bottom round is a whole cut, not mince",
("brown sugar","brown sugar"):ALT+" (palm sugar is first)",
("cannelini beans","kidney bean"):"a cannellini beans row exists; the misspelling routed to red kidney bean instead",
("cayenne pepper","cayenne pepper | cayenne pepper"):ALT+" (chilli powder is first)",
("cayenne pepper powder","cayenne pepper"):ALT+" (chilli powder is first)",
("chives","chives"):ALT+" (parsley is first)",
("chocolate chips","chocolate chip"):ALT+" (dark chocolate is first)",
("colby cheese","Colby cheese"):ALT+" (gruyere is first)",
("corn chips","corn flakes"):"corn chips are not corn flakes",
("crumbs","clam"):"panko crumbs reached a clam row",
("extra firm tofu","Dougan"):"Dougan is pressed dried tofu, a different product from a block of extra-firm",
("far","farro | Triticum spelta | Triticum dicoccum"):"'so far' is not an ingredient",
("fillets","fillet"):FORMW+" (the ingredient is snapper)",
("filling","filling | stuffing"):"the line explicitly says NOT pie filling; the ingredient is pumpkin puree",
("fruit","fruit"):"a serving line naming three dishes, linked to one of them",
("ginger powder","ground ginger"):"sand ginger is kencur, a different rhizome from ginger",
("green pepper","green pepper"):"the green pepper ROW IS THE GREEN PEPPERCORN (aliases green peppercorn, gronpeppar); the line is a long hot chili",
("green peppers","green pepper"):"same as above, the row is the green peppercorn",
("lemon wedges","lemon wedge"):ALT+" (the ingredient is lemon zest, wedges are a serving note)",
("long grain rice","long-grain rice"):ALT+" (basmati is first)",
("meat","meat | Meat"):"the ingredient is flour; 'the Meat' is what it dredges",
("muscovado sugar","muscovado"):ALT+" (palm sugar is first)",
("mustard greens","mustard greens"):ALT+" (the ingredient is 'chopped greens', spinach is first)",
("on the side","side dish"):"the ingredient is chicken stock; 'on the side' is the serving note",
("peel","zest"):PAREN+" (the note says no need to peel; the ingredient is ginger)",
("pods","legume"):"the ingredient is edamame; 'legume' is the category",
("pomegranate molasses","pomegranate molasses"):ALT+" (grape molasses is first)",
("red pepper","red bell pepper | cayenne pepper"):"a long hot red pepper is a chili, and the two rows contradict each other",
("rice syrup","brown rice syrup"):PAREN+" (the ingredient is brown sugar)",
("roast","roast"):"'light roast' describes the tahini; roast is not an ingredient",
("rum","cream"):"the 'rum' key reaches a cream row",
("salted butter","salted butter"):ALT+" (olive oil is first)",
("sauce","sauce | salsa (food)"):"the ingredient is chipotle chilies; 'sauce' is the generic category",
("sausage","Sausage"):ALT+" (bacon is first)",
("sea bass","bolognese sauce"):"a sea bass fillet reached a bolognese sauce row",
("sourdough","sourdough"):PAREN+" (the ingredient is stale bread)",
("spaghetti","spaghetti"):PAREN+" (the ingredient is noodles; spaghetti is the aside)",
("sparkling wine","sparkling wine"):ALT+" (seltzer is first)",
("spice","spice"):"'spice' is an abstract category row, aliases run Anthemis, Aroma, Baharat",
("sprouts","sprouting"):"brussels sprouts are a vegetable, 'sprouting' is the germination process",
("sunflower oil","sunflower oil"):ALT+" (vegetable oil is first)",
("sushi rice","sumeshi"):PAREN+" (the ingredient is white rice; sumeshi is seasoned rice)",
("taboon bread","Triticum durum"):"durum is a wheat species, not a bread",
("tap water","cabbage"):"tap water reached a cabbage row",
("waffles","wafer"):"a waffle is not a wafer",
("weight","Weight"):"'total prepared weight' is a measurement note; the ingredient is banana shallots",
("white bread","baguette"):"white bread routed onto the baguette row, and the line's own examples are sourdough and ciabatta",
("white fish","white fish"):ALT+" (halibut is first)",
("white onion","white onion"):ALT+" (brown onion is first)",
("white sugar","granulated sugar"):"the ingredient is brown sugar; white sugar is what it replaces",
("white wine vinegar","white wine vinegar"):ALT+" (coconut vinegar is first)",
("wild rice","wild rice"):ALT+" (basmati is first)",
("za atar","za'atar"):"the ingredient is Za'atar Spiced Almonds, so the nut, not the spice blend",
("zest","zest"):"the ingredient is lemon juice; the zest is the addition",
}
LOW={
("green chile","chili pepper | green chili | New Mexico chile"):"three rows, one of them a New Mexico landrace",
("coriander","coriander seed | Coriandrum sativum | cilantro"):"three rows spanning the seed and the leaf, which are different ingredients",
("chili","chili powder | chili pepper"):"two rows that are different things",
("paprika","bell pepper | paprika"):"hits paprika, but also drags in the bell pepper row",
("swiss chard","Brassica rapa subsp. chinensis | chard"):"the chard row is right, the bok choy row is not",
("noodles","cup noodle | noodle"):"the noodle row is right, 'cup noodle' is instant ramen",
("soybeans","tofu | soy bean"):"soy bean is right, tofu is not",
("butternut squash","pumpkin"):"the library files butternut under pumpkin",
("korean red pepper flakes","chili powder"):"gochugaru is a chili powder, but a coarser one",
("lemongrass","Lemon Gras"):"right row, but the row's canonical is misspelled",
("semisweet chocolate chips","chocolate chunk"):"chips and chunks are the same product at a different size",
("cannellini beans","cannellini beans"):"right, but two of the three lines are a bean soak-time table, not an ingredient",
("birds eye","piri piri"):"piri piri is a bird's eye chili variety",
("red beans","kidney bean"):"red beans are kidney beans, though the line is a soak-time row",
("stuffing","stuffing"):"'Stuffing Mix' is a packaged dried-bread product, the row is the dish",
("dough","dough"):"the generic dough row loses the tahini brioche",
("flour","flour"):"'AP Flour' is all-purpose flour, and that row exists",
("broth","broth"):"the ingredient is dashi broth, and a dashi row would be better",
("radish","radish"):"the line is daikon radish, and a daikon row exists",
("lime","lime"):"the ingredient is lime juice",
("lemon","lemon"):"the ingredient is lemon juice",
("orange","Orange"):"the ingredient is orange juice and orange zest",
("tea","tea"):"the line is Earl Grey, the row is generic tea",
("pepper","pepper"):"the line names salt and pepper together",
("oaxaca cheese","hebra cheese"):"queso Oaxaca is a hebra (string) cheese",
("chili flakes","red pepper flakes"):"right on one line, on the other Aleppo pepper is named first",
("bittersweet chocolate","bittersweet chocolate"):"right on most lines, on one 'semisweet' is named first",
("vegetable oil","vegetable oil"):"right on most lines, on one ghee is named first",
("spice blend","spice mix"):"tandoori masala is a specific blend, the row is generic",
("hot sauce","chili sauce | hot sauce"):"salsa is named first on that line",
("red chile","chili pepper | Spaanse peper | New Mexico chile"):"the stored label and the raw_text disagree on this line",
("demerara sugar","Demerara sugar"):"the line names butter and demerara sugar together",
("ground coriander","Coriandrum sativum"):"the species row also covers the leaf",
("ground cloves","ground cloves"):"two spices are jammed on one line by the import",
("dried oregano","dried oregano"):"three spices are jammed on one line by the import",
("flank steak","flank steak"):"skirt steak is named first",
("habanero chili","habanero"):"scotch bonnet is named first",
("beef","beef"):"the whole line is a substitution note",
("egg noodles","noodle"):"an egg noodle row would be better than the generic",
("great northern beans","white bean"):"great northern is a white bean, at a coarser grain",
("chard","Brassica rapa subsp. chinensis | chard"):"the chard row is right, the bok choy row is not",
("chicken thigh","chicken thigh | chicken leg"):"thigh is right, 'chicken leg' is the whole leg",
("chicken thighs","chicken thigh | chicken leg"):"thigh is right, 'chicken leg' is the whole leg",
("peppers","pepper"):"shishito peppers reached the generic pepper row",
("syrup","syrup | syrup"):"osmanthus syrup reached a generic syrup row, and the row is duplicated",
("yeast","yeast | Saccharomyces cerevisiae | raising agent"):"three rows for the same organism at three grains",
("rice","rice"):"'Chicken rice' and 'Jasmin rice' both reached the generic row",
("cream","cream | Malai"):"cream is right, Malai is the Indian clotted cream",
("honey","honey"):"the line reads 'Sugar / honey', so it names two",
("baguette","baguette"):"the line is a crusty baguette cut into slices",
("chilli flakes","red pepper flakes"):"Turkish pul biber and red pepper flakes are the same thing",
("black pepper","black pepper | peppercorn"):"same berry at two grains",
("chicken stock","broth | chicken broth"):"chicken broth is right, 'broth' is its generic parent",
("beef stock","broth | beef broth"):"beef broth is right, 'broth' is its generic parent",
("white pepper","peppercorn | white pepper"):"same berry at two grains",
("canola oil","rapeseed oil | canola oil"):"rapeseed and canola are the same oil, a library duplicate",
("cilantro","Coriandrum sativum | cilantro"):"the same plant on two rows, a library duplicate",
("garlic","garlic | Allium sativum"):"the same plant on two rows, a library duplicate",
("green onions","Welsh onion | scallion"):"scallion is right, Welsh onion is the coarser species row",
("scallion","Welsh onion | scallion"):"scallion is right, Welsh onion is the coarser species row",
("tomato sauce","ketchup | tomato sauce"):"tomato sauce is right, ketchup is not",
("cream cheese","fresh cheese | cream cheese"):"cream cheese is right, 'fresh cheese' is the parent",
("feta","Telemea | feta"):"feta is right, Telemea is the Romanian relative",
("pancetta","bacon | pancetta"):"pancetta is right, bacon is the coarser row",
("espresso","espresso | coffee"):"espresso is right, coffee is the parent",
("coffee powder","ground coffee | instant coffee"):"the line says instant, so one of the two rows is wrong",
("endive","endive | chicory"):"same plant group at two grains",
("spinach","spinach | Spinacia oleracea"):"the same plant on two rows, a library duplicate",
("clementine","Clementine fruit | Citrinos × clementina"):"the same fruit on two rows, a library duplicate",
("rhubarb","rhubarb | rhubarb"):"the row is duplicated in the library",
("zucchini","marrow | zucchini"):"zucchini is right, marrow is the mature form",
("lettuce","lettuce | Lactuca sativa"):"the same plant on two rows, a library duplicate",
("yogurt","yogurt | Dadiah"):"yogurt is right, Dadiah is the Indonesian buffalo-milk version",
("salsa verde","salsa verde | green sauce"):"same thing at two grains",
("chili sauce","chili sauce | hot sauce"):"the line is a black bean chili sauce, coarser than either row",
("pecorino cheese","Pecorino Romano PDO | pecorino"):"pecorino is right, the PDO row is narrower than the line",
("tapioca starch","cassava starch | cassava | tapioca"):"three rows for the same plant and its starch",
("red chillies","chili pepper | Spaanse peper"):"chili pepper is right, Spaanse peper is a Dutch variety row",
("red chilli","chili pepper | Spaanse peper"):"chili pepper is right, Spaanse peper is a Dutch variety row",
("escarole","broad-leaved endive | curly endive"):"escarole is the broad-leaved one, so one of the two rows is wrong",
("sticky rice","glutinous rice"):"same rice, different name",
("green chilies","chili pepper"):"the generic chili row loses 'green'",
("green chiles","chili pepper | green chili | New Mexico chile"):"three rows, one of them a New Mexico landrace",
("chillies","chili pepper"):"the lines are guajillo and ancho, both of which are more specific than the row",
("chilies","chili pepper"):"the generic chili row loses 'red Thai'",
("chile","chili pepper"):"the line is a Serrano, which is more specific than the row",
("pasta","pasta"):"the lines name campanelle and farfalle, which are more specific than the row",
}
