# -*- coding: utf-8 -*-
"""Hand verdicts, keyed by the matched phrase and the row set, read one pattern at a time.

DIFFERENT / OLD-ONLY are keyed (old_names, new_names, ngram).
NEW-ONLY are keyed (ngram, new_names)  -  the old matcher has no row there.
Value = (verdict, reason, confidence)   confidence "LOW" = my call could go the other way.
"""
D = {
("brown sugar","light brown sugar","light brown sugar"):("NEW-RIGHT","the line says light brown sugar and the library has that row",""),
("kombu","kelp","kelp"):("OLD-RIGHT","kombu is the named ingredient, kelp is the parenthetical gloss",""),
("oil","rapeseed oil | canola oil","canola oil"):("OLD-RIGHT","the line names 'oil', canola is one of the examples after 'such as'",""),
("lemon juice","lemon","lemon"):("OLD-RIGHT","the ingredient is the juice, not the fruit",""),
("butter | food paste","unsalted butter","unsalted butter"):("NEW-RIGHT","exact, and it drops the wrong 'food paste' co-hit",""),
("brown sugar","dark brown sugar","dark brown sugar"):("NEW-RIGHT","the line says dark brown sugar",""),
("cornstarch","water","water"):("OLD-RIGHT","water is in the parenthetical slurry note, cornstarch is the ingredient",""),
("tomato","peeled tomatoes","peeled tomatoes"):("NEW-RIGHT","canned whole peeled tomatoes is its own product",""),
("chili pepper | Spaanse peper","cayenne pepper | cayenne pepper","cayenne pepper"):("NEW-RIGHT","the publisher's own parenthetical names the variety","LOW"),
("water","ice cube","ice cube"):("OLD-RIGHT","the ice cube is an addition, water is the ingredient",""),
("vinegar","apple cider vinegar","apple cider vinegar"):("OLD-RIGHT","plain vinegar is named first, cider vinegar is the alternative",""),
("tomato","juice","juices"):("OLD-RIGHT","'juices collected' is a prep note",""),
("American cheese","Cheddar cheese","cheddar"):("OLD-RIGHT","American is the first of four alternatives",""),
("lentil","red lentil","red lentils"):("NEW-RIGHT","masoor dal is the red lentil",""),
("cut of beef","short ribs","short ribs"):("OLD-RIGHT","the line is chuck beef, short ribs is the substitute","LOW"),
("clove","ground cloves","ground cloves"):("BOTH-OK-DIFFERENT-GRANULARITY","whole vs ground clove",""),
("apple cider vinegar","white wine vinegar","white wine vinegar"):("OLD-RIGHT","cider vinegar is named first",""),
("rib eye steak | steak | standing rib roast","butter","cubes"):("OLD-RIGHT","'cubes' is a cut instruction",""),
("lime juice","must | juice","juice"):("OLD-RIGHT","lime juice is exact, 'must' is grape must and is wrong",""),
("lettuce | Lactuca sativa","Lanche","bite"):("OLD-RIGHT","'bite-size' is a cut instruction",""),
("yogurt","shortening | tallow","fat"):("OLD-RIGHT","'full fat' describes the yogurt",""),
("scallion","ling","julienne"):("OLD-RIGHT","'Julienne' is a cut instruction, 'ling' is a fish",""),
("yogurt | Dadiah","buttermilk","buttermilk"):("OLD-RIGHT","yogurt is named first, buttermilk is the alternative",""),
("cauliflower","steak","steaks"):("OLD-RIGHT","'cut into steaks' is a shape instruction",""),
("sugar","brown sugar","brown sugar"):("OLD-RIGHT","plain sugar is named first",""),
("asparagus","sharp","sharp"):("OLD-RIGHT","'a sharp angle' is a cut instruction",""),
("water","bean","beans"):("OLD-RIGHT","'enough to cover beans' is a quantity note",""),
("heavy cream","half-and-half","half and half"):("OLD-RIGHT","heavy cream is the first of three alternatives",""),
("heavy cream","cow's milk | whole milk","whole milk"):("OLD-RIGHT","heavy cream is the first of three",""),
("sugar","chopped hazelnuts","chopped hazelnuts"):("OLD-RIGHT","coarse sugar is the ingredient, hazelnuts is an optional swap",""),
("lettuce | leaf vegetable","Brassica rapa subsp. chinensis | Chinese cabbage","bok choy"):("OLD-RIGHT","'leafy greens' is the ingredient, bok choy is one example",""),
("olive","grape seed","grape seed"):("BOTH-WRONG","the ingredient is olive oil; 'olive' is the fruit and 'grape seed' is the third alternative",""),
("kosher salt","table salt","table salt"):("OLD-RIGHT","kosher salt is named first",""),
("vegetable oil","avocado oil","avocado oil"):("OLD-RIGHT","vegetable oil is the ingredient, avocado is a substitution note",""),
("egg","whole egg","whole eggs"):("BOTH-OK-DIFFERENT-GRANULARITY","same thing",""),
("shrimp","shrimp and prawn","deveined"):("BOTH-OK-DIFFERENT-GRANULARITY","both rows are shrimp, though 'deveined' is a prep word that happens to be an alias",""),
("chickpea","cooked chickpeas","cooked chickpeas"):("BOTH-OK-DIFFERENT-GRANULARITY","canned chickpeas are cooked chickpeas",""),
("olive oil","black peppercorns","black peppercorns"):("OLD-RIGHT","two ingredients are jammed on one line by the import, olive oil is first","LOW"),
("cayenne pepper | cayenne pepper","chili powder","chili powder"):("OLD-RIGHT","cayenne is named first",""),
("garlic | Allium sativum","garlic powder","garlic powder"):("NEW-RIGHT","granulated garlic is a dried product, not fresh garlic","LOW"),
("cocoa","Dutch-process cocoa","dutch process"):("OLD-RIGHT","the line allows either, so the generic row is the safer one",""),
("edible mushroom","champignon","baby portobello"):("OLD-RIGHT","'fresh mushroom' is the ingredient, the three in brackets are options",""),
("leek","rice","pale"):("OLD-RIGHT","'pale green parts' is a prep note",""),
("potato","butter","cubes"):("OLD-RIGHT","'cubes' is a cut instruction",""),
("cream | Malai","milk","milk"):("OLD-RIGHT","'sub milk' is a substitution note",""),
("bacon","grape seed oil","grape seed oil"):("OLD-RIGHT","bacon fat is named first",""),
("paneer","butter","cubes"):("OLD-RIGHT","'cut into cubes' is a prep note",""),
("nutmeg","ground nutmeg","ground nutmeg"):("BOTH-OK-DIFFERENT-GRANULARITY","whole vs ground nutmeg",""),
("coriander seed","Coriandrum sativum","ground coriander"):("OLD-RIGHT","coriander seed is exact, the species row also covers the leaf",""),
("water","broth | chicken broth","chicken stock"):("OLD-RIGHT","water is named first, stock is the alternative",""),
("garlic powder","Allium sativum | garlic clove","garlic clove"):("OLD-RIGHT","garlic powder is the ingredient, the clove is a substitution",""),
("basmati","medium grain rice","medium grain rice"):("OLD-RIGHT","basmati is named first",""),
("chocolate chip","dried fruit","dried fruit"):("OLD-RIGHT","chocolate chips is the first of five options",""),
("mirin","rice wine","rice wine"):("OLD-RIGHT","mirin is exact, 'sweet rice wine' is the gloss",""),
("milk","cow's milk | whole milk","whole milk"):("NEW-RIGHT","the line says whole milk",""),
("virgin olive oil","extra virgin olive oil","extra virgin olive oil"):("NEW-RIGHT","the line says extra virgin",""),
("lentil","brown lentils","brown lentils"):("NEW-RIGHT","whole masoor is brown, and the line says so","LOW"),
("Carnaroli","Arborio rice","arborio rice"):("OLD-RIGHT","carnaroli is named first",""),
("scallop","roe","roe"):("OLD-RIGHT","'roe removed' is a prep note",""),
("beef","minced meat","mince"):("OLD-RIGHT","beef is the ingredient, minced meat loses the species",""),
("water","broth","broth"):("OLD-RIGHT","'to make the soup broth' is a purpose note",""),
("noodle","cup noodle | noodle","noodles"):("OLD-RIGHT","the new row set adds 'cup noodle', which is instant ramen",""),
("sugar","honey","honey"):("OLD-RIGHT","sugar is named first",""),
("oil","rapeseed oil","canola"):("OLD-RIGHT","'oil' is the ingredient, canola is the third bracketed option",""),
("honey","barley malt syrup","barley malt syrup"):("OLD-RIGHT","honey is first of three",""),
("water","bread","pan"):("OLD-RIGHT","'bottom of pan' is equipment",""),
("brown sugar","barley malt syrup","barley malt syrup"):("OLD-RIGHT","brown sugar is first of three",""),
("jasmine rice","cooked rice","plain rice"):("OLD-RIGHT","jasmine rice is named first",""),
("tomato","canned tomato","canned tomato"):("OLD-RIGHT","fresh tomato is named first",""),
("harees | харисса","pepper","pepper"):("OLD-RIGHT","the old set at least contains harissa, though it also contains the harees porridge","LOW"),
("garlic | Allium sativum","salt","salt"):("OLD-RIGHT","the salt is a prep note on the garlic paste",""),
("lime juice","lime wedge","lime wedges"):("OLD-RIGHT","lime juice is the ingredient, wedges are a serving note",""),
("ice cream","-","-"):("NEW-RIGHT","'2 cups ice' is not ice cream; declining beats a wrong link, though a plain-ice row is what is really missing","LOW"),
}
