"""baseline schema

Revision ID: 72e165e6482e
Revises: 
Create Date: 2026-07-23 14:11:01.714141


Stage 2a baseline — autogenerated from models.py against the empty Postgres container, then HAND-FIXED
for the one SQLite-ism autogenerate emits verbatim that PG rejects: the date/datetime server defaults
`datetime('now')`/`date('now')` -> PG `to_char((now() AT TIME ZONE 'UTC'), ...)`, preserving the exact
UTC 'YYYY-MM-DD[ HH24:MI:SS]' text format (raw form fails CREATE TABLE: "function datetime does not
exist"). models.py keeps the SQLite-literal defaults (it still mirrors the live SQLite app); this is a
known dialect residual, so env.py runs the empty-diff gate with compare_server_default=False.
Everything else autogenerate captured faithfully (3 CHECK constraints, 3 composite PKs, regions.name
UNIQUE, the no-PK ingredient_weights Core table, the partial-unique uid index via both dialect kwargs,
Integer PKs -> SERIAL, all secondary indexes).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e165e6482e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_weights',
    sa.Column('lookup_key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('grams_per_ml', sa.Float(), nullable=False),
    sa.Column('convert_to_grams', sa.Integer(), server_default=sa.text('1'), nullable=False)
    )
    op.create_index('idx_iw_lookup', 'ingredient_weights', ['lookup_key'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('pairs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('servings', sa.Text(), nullable=True),
    sa.Column('prep_time', sa.Text(), nullable=True),
    sa.Column('cook_time', sa.Text(), nullable=True),
    sa.Column('total_time', sa.Text(), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'seed'"), nullable=False),
    sa.Column('uid', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipes_uid', 'recipes', ['uid'], unique=True, sqlite_where=sa.text('uid IS NOT NULL'), postgresql_where=sa.text('uid IS NOT NULL'))
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('schema_migrations',
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.Text(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')"), nullable=False),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('cook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('cooked_on', sa.Text(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD')"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'app'"), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_cook_log_recipe', 'cook_log', ['recipe_id'], unique=False)
    op.create_table('import_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')"), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_import_flags_recipe', 'import_flags', ['recipe_id'], unique=False)
    op.create_table('ingredient_regions',
    sa.Column('ingredient_id', sa.Text(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'region_id')
    )
    op.create_index('idx_iregions_region', 'ingredient_regions', ['region_id'], unique=False)
    op.create_table('ingredient_seasons',
    sa.Column('ingredient_id', sa.Text(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingredient_id', 'month')
    )
    op.create_index('idx_seasons_month', 'ingredient_seasons', ['month'], unique=False)
    op.create_table('ratings',
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_on', sa.Text(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')"), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('recipe_additions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Text(), nullable=False),
    sa.Column('qty', sa.Text(), nullable=True),
    sa.Column('ingredient_id', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_additions_recipe', 'recipe_additions', ['recipe_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_heading', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('qty', sa.Text(), nullable=True),
    sa.Column('ingredient_id', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('secondary_measure', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_ri_ingredient', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('idx_ri_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_line_changes',
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('new_qty', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('edit', 'remove')"),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'person_id', 'position')
    )
    op.create_index('idx_line_changes_recipe', 'recipe_line_changes', ['recipe_id'], unique=False)
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_heading', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_rs_recipe', 'recipe_steps', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rs_recipe', table_name='recipe_steps')
    op.drop_table('recipe_steps')
    op.drop_index('idx_line_changes_recipe', table_name='recipe_line_changes')
    op.drop_table('recipe_line_changes')
    op.drop_index('idx_ri_recipe', table_name='recipe_ingredients')
    op.drop_index('idx_ri_ingredient', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('idx_additions_recipe', table_name='recipe_additions')
    op.drop_table('recipe_additions')
    op.drop_table('ratings')
    op.drop_index('idx_seasons_month', table_name='ingredient_seasons')
    op.drop_table('ingredient_seasons')
    op.drop_index('idx_iregions_region', table_name='ingredient_regions')
    op.drop_table('ingredient_regions')
    op.drop_index('idx_import_flags_recipe', table_name='import_flags')
    op.drop_table('import_flags')
    op.drop_index('idx_cook_log_recipe', table_name='cook_log')
    op.drop_table('cook_log')
    op.drop_table('schema_migrations')
    op.drop_table('regions')
    op.drop_index('idx_recipes_uid', table_name='recipes', sqlite_where=sa.text('uid IS NOT NULL'), postgresql_where=sa.text('uid IS NOT NULL'))
    op.drop_table('recipes')
    op.drop_table('people')
    op.drop_table('ingredients')
    op.drop_index('idx_iw_lookup', table_name='ingredient_weights')
    op.drop_table('ingredient_weights')
    # ### end Alembic commands ###
