"""ownership user columns (rescoping R1)

Revision ID: 8a16b2f3ad3d
Revises: e2b73fb3c6af
Create Date: 2026-07-24 11:20:52.977191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a16b2f3ad3d'
down_revision: Union[str, Sequence[str], None] = 'e2b73fb3c6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cook_log', 'users', ['user_id'], ['id'])
    op.add_column('ratings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    op.add_column('recipes', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-fixed from autogenerate: name the FK constraints so the drop is valid (autogenerate emits
    # drop_constraint(None, …), which can't drop an unnamed constraint). No naming_convention is set,
    # so these are Postgres's default <table>_<col>_fkey names. upgrade() is left exactly as generated
    # (unnamed create_foreign_key -> the same default names), keeping `alembic check` empty.
    op.drop_constraint('recipes_owner_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'owner')
    op.drop_constraint('ratings_user_id_fkey', 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    op.drop_constraint('cook_log_user_id_fkey', 'cook_log', type_='foreignkey')
    op.drop_column('cook_log', 'user_id')
