#!/usr/bin/env python3
"""apply_plan_ahead_proposals.py - write the v3 proposals into a database, in lockstep.

⚠️ TAKES THE DATABASE PATH AS AN ARGUMENT AND REFUSES recipes.db WITHOUT --i-mean-live. Round 3
applies this to a COPY only.

⚠️ LOCKSTEP, AND THIS IS THE WHOLE POINT. A wait row is CONTENT: serialize_recipe_content puts it
in the blob, so writing 126 rows without touching the baselines would make every one of those 82
recipes differ from its reason='original' snapshot and mint a phantom "added a wait" annotation.
The seeded values are not a cook's edit, so the baseline has to carry them from the start.

⚠️ THE BASELINE IS PATCHED, NOT REBUILT. The stored blob is parsed, the waits and storage keys are
inserted, and it is re-dumped with content_blob's own json options. Everything else stays
byte-identical. Rebuilding the baseline from current content would declare each recipe born in its
edited state and ERASE the real annotations 49 of them are carrying.

⚠️ A BLANK-LABEL PROPOSAL IS NOT WRITTEN. 10 rows name a wait the recipe states with no duration
anywhere. label is NOT NULL and an empty one says nothing, so they wait for Andy's words.
"""
import argparse
import csv
import json
import pathlib
import sqlite3
import sys

BASE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
import planahead                                                      # noqa: E402
import snapshot_serialize                                             # noqa: E402

CSV_PATH = BASE / "previews" / "plan-ahead-proposals-v3.csv"

# ⚠️ step_id, NOT step_position AND step_check. Migration 053 replaced the slot-plus-snippet pointer
# with the step row's id and 054 dropped the two columns, so this list is what the table now has. The
# CSV still names a step POSITION, which is the right thing for a proposal to name: it was generated by
# reading the method top to bottom. apply() resolves that position to the row's id at write time.
WAIT_COLS = ("position", "kind", "label", "min_minutes", "max_minutes", "step_id",
             "ext_label", "ext_min_minutes", "ext_max_minutes", "when_kind", "when_label",
             "alongside_step_id")


# ---------------------------------------------------------------------------------------------
# The decisions taken on review, which the CSV does not say and cannot.
# ---------------------------------------------------------------------------------------------

# ⚠️ SHORT RESTS ARE OUT. A rest whose ceiling is 20 minutes or less is not time a cook plans around,
#    it is part of doing the step. Measured over the corpus: the short-rest scan found 37 genuine rests
#    and EVERY ONE is 20 minutes or less, and v3 carries none of them. This rule therefore confirms all
#    37 stay out and removes exactly ONE row v3 does carry, chocolate-chip-cookies' 5 min rest on the
#    baking sheet. Every other resting proposal is 30 minutes or more.
SHORT_REST_CEILING = 20

# ⚠️ WAITS THAT HAPPEN AT THE SAME TIME. Keyed on the step_position of the wait that OVERLAPS, valued
#    with the step_position it runs alongside. Resolved to step IDs at write time, like every other
#    pointer here. morning-buns chills the DOUGH overnight at step 5 and the BUTTER BLOCK overnight at
#    step 7, and step 8 opens "The next day" — one night, not two. Summing both told a cook to set
#    aside 25 hr for a recipe that needs about 17.
#
#    Every one of the 15 multi-wait recipes was read for this. The two closest calls are crick-cracks
#    and falafel-crackers, which each chill a dough overnight and then chill rolled sheets 4 hr to
#    overnight — SEQUENTIAL, because the second chill cannot start until the dough has been rolled the
#    next day. The rest are rise-then-rise or soak-then-rest, which are sequential by construction.
ALONGSIDE = {
    ("morning-buns-with-orange-blossom-glaze", 6): 4,
}

# ⚠️ A TIME FIELD THAT REPEATS A WAIT SAYS IT TWICE. Once the wait is a row of its own, the note folded
#    into prep_time or cook_time is the same fact in a worse place, and the breakdown already reads it.
#    Each correction below removes ONLY the part that duplicates a wait this seed writes.
#
#    ⚠️ spiced-scallops' cook_time ALSO says "plus cooling", and that is NOT touched: no proposed wait
#    covers a cooling period, so it is the only place that fact is recorded.
TIME_FIELD_FIXES = {
    # bo-luc-lac's prep_time folded the 8 hr marinade into preparation, which is what the CSV's
    # 'flagged: prep_time' row records. 20 min is the actual hands-on time.
    "bo-luc-lac-shaking-beef": {"prep_time": "20 min"},
    "gai-yang": {"cook_time": "40 min"},                    # was "40 min (plus 2 hr+ marinating)"
    "mussakhan": {"cook_time": "35 min"},                   # was "35 min (plus 1-3 hr marinating)"
    "spiced-scallops-with-saffron-beurre-blanc": {"prep_time": "30 mins"},   # was "..., plus 1 hour soaking"
}
STORE_COLS = ("position", "where_kept", "applies_to", "label", "min_minutes", "max_minutes")


def _i(v):
    return None if v in (None, "") else int(v)


def load(path=CSV_PATH):
    """CSV -> {recipe_id: {"waits": [...], "storage": [...]}}, blanks and non-rows dropped."""
    out, skipped = {}, {"blank": 0, "excluded": 0, "flagged": 0}
    for r in csv.DictReader(path.open()):
        t = r["type"]
        if t == "excluded":
            skipped["excluded"] += 1
            continue
        if t.startswith("flagged"):
            skipped["flagged"] += 1
            continue
        if not (r["label"] or "").strip():
            skipped["blank"] += 1
            continue
        if t == "wait" and r["kind"] == "resting":
            lo, hi = planahead.read_duration(r["label"])
            ceiling = hi if hi is not None else lo
            if ceiling is not None and ceiling <= SHORT_REST_CEILING:
                skipped.setdefault("short_rest", 0)
                skipped["short_rest"] += 1
                skipped.setdefault("short_rest_rows", []).append(
                    f'{r["recipe_id"]} step {r["step_position"]}: {r["label"]}')
                continue
        bucket = out.setdefault(r["recipe_id"], {"waits": [], "storage": []})
        if t == "wait":
            bucket["waits"].append(dict(
                kind=r["kind"] if r["kind"] in planahead.KINDS else "other",
                label=r["label"], min_minutes=_i(r["min_minutes"]), max_minutes=_i(r["max_minutes"]),
                step_position=_i(str(r["step_position"]).split(".")[0]),
                ext_label=(r["ext_label"] or None),
                ext_min_minutes=_i(r["ext_min_minutes"]), ext_max_minutes=_i(r["ext_max_minutes"]),
                when_kind=r["when_kind"] or "always",
                when_label=(r["when_label"] or None) if r["when_kind"] == "only_if" else None,
                source_sentence=r["source_sentence"] or ""))
        elif t == "storage":
            bucket["storage"].append(dict(
                where_kept=r["kind"] if r["kind"] in planahead.WHERES else "other",
                applies_to=None, label=r["label"],
                min_minutes=_i(r["min_minutes"]), max_minutes=_i(r["max_minutes"])))
    return out, skipped


def _patch_baseline(stored, waits, storage, recipe_fields=None):
    """Insert the waits and storage keys into a stored baseline, leaving the rest byte-identical.

    ⚠️ THE KEYS ARE OMITTED WHEN EMPTY, exactly as content_blob omits them, so a recipe with no
    proposals keeps a blob that still compares byte-equal to what the serializer produces.

    ⚠️ recipe_fields PATCHES THE HEADER IN THE SAME BREATH, and it has to. prep_time and cook_time are
    in SNAPSHOT_RECIPE_FIELDS, so correcting one on the live row without correcting the baseline mints
    a "your changes" mark saying the cook edited a time they never touched. Same lockstep argument as
    the waits, one level up."""
    body = json.loads(stored)
    if recipe_fields:
        body["recipe"].update(recipe_fields)
    for key, rows, fields in (("waits", waits, snapshot_serialize.SNAPSHOT_WAIT_FIELDS),
                              ("storage", storage, snapshot_serialize.SNAPSHOT_STORAGE_FIELDS)):
        if rows:
            body[key] = [{k: r.get(k) for k in fields} for r in rows]
        else:
            body.pop(key, None)
    return json.dumps(body, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def apply(db, plan, dry=False):
    c = sqlite3.connect(db)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA foreign_keys=ON")
    wrote = {"recipes": 0, "waits": 0, "storage": 0, "baselines": 0, "no_baseline": []}
    missing = []
    # ⚠️ A HEADER CORRECTION FOR A RECIPE OUTSIDE THE PLAN WOULD BE SILENTLY SKIPPED, because the
    #    corrections are applied inside the per-recipe loop below so they share its transaction and its
    #    baseline patch. Fail instead of dropping one.
    astray = sorted(set(TIME_FIELD_FIXES) - set(plan))
    if astray:
        raise SystemExit(f"ABORT: TIME_FIELD_FIXES names {astray}, which the plan does not cover, so "
                         f"the correction would never be applied and its baseline never patched.")
    off_map = sorted({r for r, _ in ALONGSIDE} - set(plan))
    if off_map:
        raise SystemExit(f"ABORT: ALONGSIDE names {off_map}, which the plan does not cover.")
    for rid in sorted(plan):
        if not c.execute("SELECT 1 FROM recipes WHERE id=?", (rid,)).fetchone():
            missing.append(rid)
            continue
        # ⚠️ STEP ORDER, NOT CSV ORDER. The CSV sorts step_position as a STRING, so morning-buns
        #    listed steps 15, 18, 20, 24, 5, 7. A cook reads the method top to bottom and the
        #    breakdown has to agree with it. A wait with no step keeps its relative place at the end.
        waits = sorted(plan[rid]["waits"],
                       key=lambda w: (w.get("step_position") is None, w.get("step_position") or 0))
        storage = plan[rid]["storage"]
        c.execute("DELETE FROM recipe_waits WHERE recipe_id=?", (rid,))
        c.execute("DELETE FROM recipe_storage WHERE recipe_id=?", (rid,))
        # ⚠️ THE HEADER CORRECTION GOES IN THE SAME TRANSACTION AS ITS BASELINE PATCH BELOW, which is
        #    what keeps it from reading as an edit the cook made.
        for col, val in (TIME_FIELD_FIXES.get(rid) or {}).items():
            c.execute(f"UPDATE recipes SET {col}=? WHERE id=?", (val, rid))
            wrote.setdefault("time_fields", 0)
            wrote["time_fields"] += 1
        # ⚠️ THE POSITION IS RESOLVED TO A ROW ID HERE, ONCE, AGAINST THE STEPS AS THEY STAND. That is
        #    the whole of what the snippet used to be for. This read the step's TEXT to build a check
        #    out of the source sentence, and none of that is needed: the id identifies the row, so a
        #    later save that renumbers or rewords the step cannot move or break the link.
        #
        #    A position naming no ordinary step of the recipe resolves to NULL rather than to a guess,
        #    which is the same rule app.write_plan_ahead applies to an incoming step_id.
        step_id_at = {r["position"]: r["id"] for r in c.execute(
            "SELECT id, position FROM recipe_steps WHERE recipe_id=? AND is_heading=0", (rid,))}
        for pos, w in enumerate(waits):
            sp = w.get("step_position")
            # ⚠️ THE OVERLAP IS RESOLVED THROUGH STEP POSITIONS TO STEP IDS, like every other pointer
            #    here. ALONGSIDE names the step_position the wait runs alongside, and a map entry whose
            #    target is not an ordinary step of this recipe is dropped rather than half-written: the
            #    table refuses an 'alongside' with no target, so a silent None here would 500 the seed.
            aside_pos = ALONGSIDE.get((rid, sp))
            aside_id = step_id_at.get(aside_pos) if aside_pos is not None else None
            w = dict(w, step_id=step_id_at.get(sp), alongside_step_id=aside_id)
            if aside_id is not None:
                if aside_id == w["step_id"]:
                    raise SystemExit(f"ABORT: {rid} step {sp} would run alongside its own step")
                w["when_kind"] = "alongside"
            w.pop("step_position", None)
            w.pop("source_sentence", None)
            row = dict(w, position=pos)
            c.execute(f"INSERT INTO recipe_waits (recipe_id,{','.join(WAIT_COLS)}) "
                      f"VALUES (?,{','.join('?' * len(WAIT_COLS))})",
                      (rid, *(row[k] for k in WAIT_COLS)))
            wrote["waits"] += 1
        for pos, x in enumerate(storage):
            row = dict(x, position=pos)
            c.execute(f"INSERT INTO recipe_storage (recipe_id,{','.join(STORE_COLS)}) "
                      f"VALUES (?,{','.join('?' * len(STORE_COLS))})",
                      (rid, *(row[k] for k in STORE_COLS)))
            wrote["storage"] += 1
        # ---- LOCKSTEP: the baseline carries the same rows, in the same transaction ----
        stored = c.execute("SELECT content FROM recipe_snapshots WHERE recipe_id=? "
                           "AND reason='original'", (rid,)).fetchone()
        if stored is None:
            wrote["no_baseline"].append(rid)          # never mint one; see snapshot_original
        else:
            db_waits = [dict(r) for r in c.execute(
                "SELECT * FROM recipe_waits WHERE recipe_id=? ORDER BY position, id", (rid,))]
            db_store = [dict(r) for r in c.execute(
                "SELECT * FROM recipe_storage WHERE recipe_id=? ORDER BY position, id", (rid,))]
            patched = _patch_baseline(stored["content"], db_waits, db_store,
                                      TIME_FIELD_FIXES.get(rid))
            if patched != stored["content"]:
                c.execute("UPDATE recipe_snapshots SET content=? WHERE recipe_id=? "
                          "AND reason='original'", (patched, rid))
                wrote["baselines"] += 1
        wrote["recipes"] += 1
    if dry:
        c.rollback()
    else:
        c.commit()
    c.close()
    return wrote, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("db")
    ap.add_argument("--dry", action="store_true")
    ap.add_argument("--i-mean-live", action="store_true")
    a = ap.parse_args()
    db = pathlib.Path(a.db).resolve()
    if db.name == "recipes.db" and db.parent == BASE and not a.i_mean_live:
        sys.exit("refusing to write live recipes.db without --i-mean-live")
    plan, skipped = load()
    print(f"plan: {len(plan)} recipes, "
          f"{sum(len(v['waits']) for v in plan.values())} waits, "
          f"{sum(len(v['storage']) for v in plan.values())} storage")
    print(f"  not written: {skipped}")
    wrote, missing = apply(db, plan, dry=a.dry)
    print(f"{'DRY RUN' if a.dry else 'WROTE'} -> {db}")
    for k, v in wrote.items():
        print(f"  {k}: {v if not isinstance(v, list) else (len(v), v[:6])}")
    if missing:
        print(f"  ⚠️ {len(missing)} proposal recipes are not in this database: {missing[:8]}")


if __name__ == "__main__":
    main()
