#!/usr/bin/env python3
"""backfill_qty_unit.py — one-off backfill: populate the additive quantity+unit columns
(migration 015) for existing rows by re-parsing the stored free-text `qty`.

This is the repo's FIRST data-transforming step: 96% of qty data is source='app', persistent in
recipes.db and NOT regenerated by build_db, so — unlike migrations 011/012 (which only added
columns and let import fill them) — the existing rows need a real backfill. The split can't live in
the SQL migration (migrate.py runs executescript, which can't call parse_amount), so it lives here.

Uses import_cleanup.split_qty — the SAME rule the seed-load path (build_db) uses, so seed/test and
app rows split identically. The original `qty` column is left UNTOUCHED (source-of-truth).

Guarded + idempotent: only non-heading rows WHERE quantity IS NULL are touched. Because this runs
OUTSIDE migrate.py's schema_migrations tracker, that WHERE guard is what makes re-running safe — a
second run finds nothing (every processed row has quantity set, even "" for empty qty). Heading rows
are left NULL (they carry no qty). One transaction; a real run only.

Run FIRST:  python3 backup.py                       # snapshot recipes.db (safety)
Then:       python3 scripts/backfill_qty_unit.py --dry-run   # report the split, write nothing
            python3 scripts/backfill_qty_unit.py             # write quantity+unit
"""
import argparse
import sqlite3
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))          # import the app's amount parser
from import_cleanup import split_qty        # noqa: E402

DB = BASE_DIR / "recipes.db"


def _bucket(qty, quantity, unit):
    """Classify a produced split for the distribution report (matches the corpus diagnostic).
    Count-nouns ("4 cloves" -> unit="cloves") land in number+unit (unit is set). The number-only
    vs fallback split (both unit="") is decided by letters: a pure amount expression ("2", "1 1/2",
    "2-3") has none; an irreducible fallback ("pinch", "2 lb / 1 kg", "3 + 2 tbsp") has letters."""
    if not (qty or "").strip():
        return "empty"
    if unit:
        return "number+unit"
    # unit == "": a pure amount expression is number-only — including a "N to M" range, whose only
    # letters are the connector "to". Any OTHER letters ("pinch", "lb / kg", "+ tbsp") -> fallback.
    import re
    letters = re.sub(r"[^A-Za-z]", "", quantity).lower()
    return "number-only" if letters in ("", "to") else "fallback"


def backfill(dry_run=False):
    if not DB.exists():
        sys.exit(f"No database: {DB} (run build_db.py first)")
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT id, qty FROM recipe_ingredients WHERE is_heading = 0 AND quantity IS NULL"
    ).fetchall()

    dist = {"number+unit": 0, "number-only": 0, "empty": 0, "fallback": 0}
    examples = {}
    updates = []
    for r in rows:
        quantity, unit = split_qty(r["qty"])
        b = _bucket(r["qty"], quantity, unit)
        dist[b] += 1
        examples.setdefault(b, (r["qty"], quantity, unit))
        updates.append((quantity, unit, r["id"]))

    if not dry_run:
        conn.executemany(
            "UPDATE recipe_ingredients SET quantity = ?, unit = ? WHERE id = ?", updates
        )
        conn.commit()
    conn.close()

    total = len(rows)
    print(f"{'DRY-RUN — ' if dry_run else ''}backfilled {total} non-heading rows (quantity IS NULL):")
    for b in ("number+unit", "number-only", "empty", "fallback"):
        n = dist[b]
        pct = (100 * n / total) if total else 0
        ex = examples.get(b)
        exs = f"   e.g. {ex[0]!r} -> quantity={ex[1]!r} unit={ex[2]!r}" if ex else ""
        print(f"  {b:12s} {n:5d}  ({pct:4.1f}%){exs}")
    if total == 0:
        print("  (nothing to do — all non-heading rows already have quantity set; idempotent no-op)")
    return dist


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="report the split; write nothing")
    args = ap.parse_args()
    backfill(dry_run=args.dry_run)
