#!/usr/bin/env python3.13
"""Regenerate tests/fixtures/sized-piece.json from the Python sized-piece reader.

READ-ONLY on every database: it opens none. Run it when R1's grammar changes ON PURPOSE, and read
the diff before committing it, because this fixture is the only thing holding
import_cleanup.sized_piece_text and static/scaler.js's sizedPiece to one answer.

⚠️ WHY A FIXTURE RATHER THAN A WORD-LIST COMPARISON. The first guard compared the PIECE_WORDS list
   and four integer examples. The two grammars had already diverged on everything else: the Python
   side writes "1/2-inch slices", "1 to 2-inch chunks", "roughly 3 cm chunk", "about 2-inch piece",
   "4 in. piece" and "1 1/2-inch piece", and the JS read none of them, so all six fell through to
   the ordinary number scaler and had their SIZE doubled. A list comparison cannot see that. A
   round trip over the strings the writer actually emits can.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import import_cleanup as ic                                                   # noqa: E402

CASES = [
    # what the writer actually produces, across its whole number grammar
    "1-inch knob", "2-inch piece", "3-inch section", "1½-inch piece", "1 1/2-inch piece",
    "1/2-inch slices", "3/4-inch piece", "¾-inch piece", "1 to 2-inch chunks",
    "roughly 3 cm chunk", "about 2-inch piece", "up to 2-inch piece", "4 in. piece",
    "3 millimeter slice", "2.5-inch stick", "5mm slice", '2" chunk', "1-inch knobs",
    # already scaled, so it has to round-trip rather than compound
    "2 × 1-inch knob", "½ × 1-inch knob", "3 × 1/2-inch slices",
    # NOT a sized piece, each for its own reason
    "1 cup", "2 cups", "½", "1 pound", "", "1-inch cubes", "2 tbsp", "1 stick",
    "2 cups 1-inch cubes of bread", "1 x 2-inch piece", "about 1/2 cup per person",
]
WHY = ("Generated by scripts/gen_sized_piece_fixture.py from import_cleanup.sized_piece_text, "
       "which is the reader on the side that WRITES the amount. static/scaler.js's sizedPiece has "
       "to agree with it string for string: a shape the writer emits and the scaler cannot read "
       "falls through to the ordinary number scaler and has its SIZE multiplied, which is the one "
       "outcome R1 exists to prevent. A fresh review found six such shapes. Both suites assert "
       "against this file.")


def main():
    cases = []
    for s in CASES:
        count, piece = ic.sized_piece_text(s)
        cases.append({"amount": s, "count": count, "piece": piece})
    out = pathlib.Path(HERE.parent / "tests" / "fixtures" / "sized-piece.json")
    out.write_text(json.dumps({"why": WHY, "cases": cases}, indent=1, ensure_ascii=False) + "\n")
    pieces = sum(1 for c in cases if c["count"])
    print(f"{out}: {len(cases)} cases, {pieces} of them sized pieces")


if __name__ == "__main__":
    main()
